// Generated by telar-transpiler — do not edit manually
#![allow(clippy::all)]
#[allow(unused_imports)] use telar::*;
#[allow(unused_imports)] use crate::*;
#[allow(unused_imports)] use crate::shared::components::card::{card, CardProps};
#[allow(unused_imports)] use crate::shared::components::code_line::{code_line, CodeLineProps};
#[allow(unused_imports)] use crate::shared::components::doc_header::{doc_header, DocHeaderProps};
#[allow(unused_imports)] use crate::shared::components::example::{example, ExampleProps};

#[derive(::telar::Props)]
pub struct OpacityProps {}

#[allow(dead_code)]
fn style_center() -> LayoutStyle {
    #[allow(unused_variables)] let theme = telar::Theme::<core::theme::SandboxTheme>::default();
    LayoutStyle::new()
        .align_items(AlignItems::CENTER)
        .justify_content(JustifyContent::CENTER)
}

#[allow(dead_code, unused_variables, unused_mut)]
pub fn opacity(props: OpacityProps, children: Children) -> Result<Box<dyn LayoutItem>, LayoutError> {
    let __owner = telar::owner_scope();
    #[allow(unused_imports)] use telar::use_theme;
    #[allow(unused_variables)] let theme = telar::Theme::<core::theme::SandboxTheme>::default();

    let __col_0 = {
        let __node_0 = doc_header(DocHeaderProps::props().kicker("SURFACES").title("Opacity & layers").desc("opacity fades a box and everything inside it as a single layer, so nested transparencies multiply the way you would expect.").build(), Children::default())?;
        let __node_1 = {
            let __deferred = Children::new(
                {
                    let theme = theme.clone();
                move || {
                    let theme = theme.clone();
                    let mut __slots = Slots::new();
                    let mut __children: Vec<Box<dyn LayoutItem>> = Vec::new();
                    let __node_2 = {
                        let __deferred = Children::new(
                            {
                                let theme = theme.clone();
                            move || {
                                let theme = theme.clone();
                                let mut __slots = Slots::new();
                                let mut __children: Vec<Box<dyn LayoutItem>> = Vec::new();
                                let __row_0 = {
                                    let __sbox_0 = {
                                        let __text_0 = {
                                            Text::declaring(
                                                || "1.0".to_string(),
                                                LayoutStyle::new(),
                                                move |__inherited: TextStyle| __inherited,
                                            )?
                                        };
                                        StyledContainer::new(style_center().flex_column().width(120.0).height(72.0), { let theme = theme.clone(); move |_| RectStyle::default().with_fill(theme.get().danger).with_radius(BorderRadius::all(10.0)) }, children![__text_0])?.with_opacity(|| 1.0)
                                    };
                                    let __sbox_1 = {
                                        let __text_1 = {
                                            Text::declaring(
                                                || "0.6".to_string(),
                                                LayoutStyle::new(),
                                                move |__inherited: TextStyle| __inherited,
                                            )?
                                        };
                                        StyledContainer::new(style_center().flex_column().width(120.0).height(72.0), { let theme = theme.clone(); move |_| RectStyle::default().with_fill(theme.get().danger).with_radius(BorderRadius::all(10.0)) }, children![__text_1])?.with_opacity(|| 0.6)
                                    };
                                    let __sbox_2 = {
                                        let __text_2 = {
                                            Text::declaring(
                                                || "0.3".to_string(),
                                                LayoutStyle::new(),
                                                move |__inherited: TextStyle| __inherited,
                                            )?
                                        };
                                        StyledContainer::new(style_center().flex_column().width(120.0).height(72.0), { let theme = theme.clone(); move |_| RectStyle::default().with_fill(theme.get().danger).with_radius(BorderRadius::all(10.0)) }, children![__text_2])?.with_opacity(|| 0.3)
                                    };
                                    let __sbox_3 = {
                                        let __text_3 = {
                                            Text::declaring(
                                                || "0.1".to_string(),
                                                LayoutStyle::new(),
                                                move |__inherited: TextStyle| __inherited,
                                            )?
                                        };
                                        StyledContainer::new(style_center().flex_column().width(120.0).height(72.0), { let theme = theme.clone(); move |_| RectStyle::default().with_fill(theme.get().danger).with_radius(BorderRadius::all(10.0)) }, children![__text_3])?.with_opacity(|| 0.1)
                                    };
                                    Container::new(LayoutStyle::new().flex_row().gap(14.0).flex_wrap(), children![__sbox_0, __sbox_1, __sbox_2, __sbox_3])?.declaring({ let theme = theme.clone(); move || Declared::default().with_font_size(16.0).with_color(theme.get().on_primary) })
                                };
                                __children.push(box_item(__row_0));
                                __slots.extend_default(__children);
                                Ok(__slots)
                            }
                            }
                        );
                        card(CardProps::props().build(), __deferred)?
                    };
                    __children.push(box_item(__node_2));
                    let __node_3 = code_line(CodeLineProps::props().code("box fill:$theme.danger opacity:0.3").build(), Children::default())?;
                    __children.push(box_item(__node_3));
                    __slots.extend_default(__children);
                    Ok(__slots)
                }
                }
            );
            example(ExampleProps::props().title("A single fill at descending opacity").build(), __deferred)?
        };
        let __node_4 = {
            let __deferred = Children::new(
                {
                    let theme = theme.clone();
                move || {
                    let theme = theme.clone();
                    let mut __slots = Slots::new();
                    let mut __children: Vec<Box<dyn LayoutItem>> = Vec::new();
                    let __node_5 = {
                        let __deferred = Children::new(
                            {
                                let theme = theme.clone();
                            move || {
                                let theme = theme.clone();
                                let mut __slots = Slots::new();
                                let mut __children: Vec<Box<dyn LayoutItem>> = Vec::new();
                                let __sbox_4 = {
                                    let __text_4 = {
                                        Text::declaring(
                                            || "gradient at 0.75".to_string(),
                                            LayoutStyle::new(),
                                            { let theme = theme.clone(); move |__inherited: TextStyle| __inherited.with_font_size(16.0).with_color(theme.get().on_primary) },
                                        )?
                                    };
                                    StyledContainer::new(style_center().flex_column().height(80.0), { let theme = theme.clone(); move |r| RectStyle { fill: Some(Paint::Gradient(Gradient::linear(Point::new(r.x, r.y + r.height * 0.5), Point::new(r.x + r.width, r.y + r.height * 0.5), &[(0.0, theme.get().primary), (0.5, theme.get().purple), (1.0, theme.get().danger)]))), border: None, shadow: None, radius: BorderRadius::all(12.0) } }, children![__text_4])?.with_opacity(|| 0.75)
                                };
                                __children.push(box_item(__sbox_4));
                                __slots.extend_default(__children);
                                Ok(__slots)
                            }
                            }
                        );
                        card(CardProps::props().build(), __deferred)?
                    };
                    __children.push(box_item(__node_5));
                    let __node_6 = code_line(CodeLineProps::props().code("box fill:linear(horizontal, $theme.primary, $theme.danger) opacity:0.75").build(), Children::default())?;
                    __children.push(box_item(__node_6));
                    __slots.extend_default(__children);
                    Ok(__slots)
                }
                }
            );
            example(ExampleProps::props().title("Layer opacity applies to a gradient and its label together").build(), __deferred)?
        };
        let __node_7 = {
            let __deferred = Children::new(
                {
                    let theme = theme.clone();
                move || {
                    let theme = theme.clone();
                    let mut __slots = Slots::new();
                    let mut __children: Vec<Box<dyn LayoutItem>> = Vec::new();
                    let __node_8 = {
                        let __deferred = Children::new(
                            {
                                let theme = theme.clone();
                            move || {
                                let theme = theme.clone();
                                let mut __slots = Slots::new();
                                let mut __children: Vec<Box<dyn LayoutItem>> = Vec::new();
                                let __sbox_5 = {
                                    let __text_5 = {
                                        Text::declaring(
                                            || "outer · 0.6".to_string(),
                                            LayoutStyle::new(),
                                            { let theme = theme.clone(); move |__inherited: TextStyle| __inherited.with_font_size(12.0).with_color(theme.get().on_primary) },
                                        )?
                                    };
                                    let __sbox_6 = {
                                        let __text_6 = {
                                            Text::declaring(
                                                || "inner · 0.6".to_string(),
                                                LayoutStyle::new(),
                                                { let theme = theme.clone(); move |__inherited: TextStyle| __inherited.with_font_size(14.0).with_color(theme.get().on_primary) },
                                            )?
                                        };
                                        StyledContainer::new(style_center().flex_column().flex_grow(1.0), { let theme = theme.clone(); move |_| RectStyle::default().with_fill(theme.get().danger).with_radius(BorderRadius::all(8.0)) }, children![__text_6])?.with_opacity(|| 0.6)
                                    };
                                    StyledContainer::new(LayoutStyle::new().flex_column().height(120.0).padding_all(14.0).gap(8.0), { let theme = theme.clone(); move |_| RectStyle::default().with_fill(theme.get().primary).with_radius(BorderRadius::all(10.0)) }, children![__text_5, __sbox_6])?.with_opacity(|| 0.6)
                                };
                                __children.push(box_item(__sbox_5));
                                __slots.extend_default(__children);
                                Ok(__slots)
                            }
                            }
                        );
                        card(CardProps::props().build(), __deferred)?
                    };
                    __children.push(box_item(__node_8));
                    let __node_9 = code_line(CodeLineProps::props().code("box opacity:0.6   >   box opacity:0.6   (layers multiply)").build(), Children::default())?;
                    __children.push(box_item(__node_9));
                    __slots.extend_default(__children);
                    Ok(__slots)
                }
                }
            );
            example(ExampleProps::props().title("Nested — outer 0.6 × inner 0.6 combine to about 0.36").build(), __deferred)?
        };
        Container::new(LayoutStyle::new().flex_column().gap(20.0), children![__node_0, __node_1, __node_4, __node_7])?
    };
    Ok(Box::new(__col_0))
}
