// Generated by telar-transpiler — do not edit manually
#![allow(clippy::all)]
#[allow(unused_imports)] use telar::*;
#[allow(unused_imports)] use super::*;

#[allow(dead_code)]
fn style_center() -> LayoutStyle {
    LayoutStyle::new()
        .align_items(AlignItems::CENTER)
        .justify_content(JustifyContent::CENTER)
}

#[allow(dead_code, unused_variables, unused_mut)]
pub fn features_sizing() -> Result<Box<dyn LayoutItem>, LayoutError> {
    let __owner = telar::owner_scope();
    #[allow(unused_imports)] use telar::use_theme;
    let __col_0 = {
        let __node_0 = doc_header(DocHeaderProps { kicker: "FOUNDATIONS", title: "Sizing & grid", desc: "Size in pixels or percentages, clamp with min/max, and reach for the grid when you need aligned columns or a responsive gallery." })?;
        let __node_1 = {
            let mut __slots = Slots::new();
            let mut __children: Vec<Box<dyn LayoutItem>> = Vec::new();
            let __node_2 = {
                let mut __slots = Slots::new();
                let mut __children: Vec<Box<dyn LayoutItem>> = Vec::new();
                let __sbox_0 = {
                    StyledContainer::new(LayoutStyle::new().flex_column().width(120.0).height(26.0), move |_| RectStyle::default().with_fill(use_theme::<core::theme::SandboxTheme>().primary()).with_radius(BorderRadius::all(6.0)), children![])?
                };
                __children.push(box_item(__sbox_0));
                let __sbox_1 = {
                    StyledContainer::new(LayoutStyle::new().flex_column().width(SizeDimension::Percent(0.5)).height(26.0), move |_| RectStyle::default().with_fill(use_theme::<core::theme::SandboxTheme>().primary()).with_radius(BorderRadius::all(6.0)), children![])?
                };
                __children.push(box_item(__sbox_1));
                let __sbox_2 = {
                    StyledContainer::new(LayoutStyle::new().flex_column().width(SizeDimension::Percent(1.0)).height(26.0), move |_| RectStyle::default().with_fill(use_theme::<core::theme::SandboxTheme>().primary()).with_radius(BorderRadius::all(6.0)), children![])?
                };
                __children.push(box_item(__sbox_2));
                __slots.extend_default(__children);
                card(CardProps { gap: 10.0, ..Default::default() }, __slots)?
            };
            __children.push(box_item(__node_2));
            let __node_3 = code_line(CodeLineProps { code: "box width:120   ·   width:50%   ·   width:100%" })?;
            __children.push(box_item(__node_3));
            __slots.extend_default(__children);
            example(ExampleProps { title: "Fixed vs percentage width" }, __slots)?
        };
        let __node_4 = {
            let mut __slots = Slots::new();
            let mut __children: Vec<Box<dyn LayoutItem>> = Vec::new();
            let __node_5 = {
                let mut __slots = Slots::new();
                let mut __children: Vec<Box<dyn LayoutItem>> = Vec::new();
                let __row_0 = {
                    let __sbox_3 = {
                        StyledContainer::new(LayoutStyle::new().flex_column().min_width(200.0).flex_grow(1.0).height(30.0), move |_| RectStyle::default().with_fill(use_theme::<core::theme::SandboxTheme>().purple).with_radius(BorderRadius::all(6.0)), children![])?
                    };
                    let __sbox_4 = {
                        StyledContainer::new(LayoutStyle::new().flex_column().min_width(200.0).flex_grow(1.0).height(30.0), move |_| RectStyle::default().with_fill(use_theme::<core::theme::SandboxTheme>().purple).with_radius(BorderRadius::all(6.0)), children![])?
                    };
                    let __sbox_5 = {
                        StyledContainer::new(LayoutStyle::new().flex_column().min_width(200.0).flex_grow(1.0).height(30.0), move |_| RectStyle::default().with_fill(use_theme::<core::theme::SandboxTheme>().purple).with_radius(BorderRadius::all(6.0)), children![])?
                    };
                    Container::new(LayoutStyle::new().flex_row().gap(10.0).flex_wrap(), children![__sbox_3, __sbox_4, __sbox_5])?
                };
                __children.push(box_item(__row_0));
                __slots.extend_default(__children);
                card(CardProps { ..Default::default() }, __slots)?
            };
            __children.push(box_item(__node_5));
            let __node_6 = code_line(CodeLineProps { code: "box min_width:200 grow:1   (also max_width, min_height, max_height)" })?;
            __children.push(box_item(__node_6));
            __slots.extend_default(__children);
            example(ExampleProps { title: "min_width — a box refuses to shrink below its floor, then wraps" }, __slots)?
        };
        let __node_7 = {
            let mut __slots = Slots::new();
            let mut __children: Vec<Box<dyn LayoutItem>> = Vec::new();
            let __node_8 = {
                let mut __slots = Slots::new();
                let mut __children: Vec<Box<dyn LayoutItem>> = Vec::new();
                let __node_9 = {
                    let __sbox_6 = {
                        let __text_0 = {
                            Text::declaring(
                                || "1".to_string(),
                                LayoutStyle::new(),
                                move |__inherited: TextStyle| __inherited,
                            )?
                        };
                        StyledContainer::new(style_center().flex_column().height(44.0), move |_| RectStyle::default().with_fill(use_theme::<core::theme::SandboxTheme>().cyan).with_radius(BorderRadius::all(6.0)), children![__text_0])?
                    };
                    let __sbox_7 = {
                        let __text_1 = {
                            Text::declaring(
                                || "2".to_string(),
                                LayoutStyle::new(),
                                move |__inherited: TextStyle| __inherited,
                            )?
                        };
                        StyledContainer::new(style_center().flex_column().height(44.0), move |_| RectStyle::default().with_fill(use_theme::<core::theme::SandboxTheme>().cyan).with_radius(BorderRadius::all(6.0)), children![__text_1])?
                    };
                    let __sbox_8 = {
                        let __text_2 = {
                            Text::declaring(
                                || "3".to_string(),
                                LayoutStyle::new(),
                                move |__inherited: TextStyle| __inherited,
                            )?
                        };
                        StyledContainer::new(style_center().flex_column().height(44.0), move |_| RectStyle::default().with_fill(use_theme::<core::theme::SandboxTheme>().cyan).with_radius(BorderRadius::all(6.0)), children![__text_2])?
                    };
                    let __sbox_9 = {
                        let __text_3 = {
                            Text::declaring(
                                || "span 2".to_string(),
                                LayoutStyle::new(),
                                move |__inherited: TextStyle| __inherited,
                            )?
                        };
                        StyledContainer::new(style_center().flex_column().height(44.0).grid_column_span(2), move |_| RectStyle::default().with_fill(use_theme::<core::theme::SandboxTheme>().cyan).with_radius(BorderRadius::all(6.0)), children![__text_3])?
                    };
                    let __sbox_10 = {
                        let __text_4 = {
                            Text::declaring(
                                || "5".to_string(),
                                LayoutStyle::new(),
                                move |__inherited: TextStyle| __inherited,
                            )?
                        };
                        StyledContainer::new(style_center().flex_column().height(44.0), move |_| RectStyle::default().with_fill(use_theme::<core::theme::SandboxTheme>().cyan).with_radius(BorderRadius::all(6.0)), children![__text_4])?
                    };
                    Container::new(LayoutStyle::new().display_grid().grid_template_columns(vec![TemplateTrack::repeat(3, TemplateTrack::fr(1.0))]).gap(10.0), children![__sbox_6, __sbox_7, __sbox_8, __sbox_9, __sbox_10])?.declaring(move || Declared::default().with_font_size(13.0).with_color(use_theme::<core::theme::SandboxTheme>().on_primary()))
                };
                __children.push(box_item(__node_9));
                __slots.extend_default(__children);
                card(CardProps { ..Default::default() }, __slots)?
            };
            __children.push(box_item(__node_8));
            let __node_10 = code_line(CodeLineProps { code: "grid cols:3 gap:10      >      box span:2" })?;
            __children.push(box_item(__node_10));
            __slots.extend_default(__children);
            example(ExampleProps { title: "Grid — fixed column count with repeat(3, 1fr)" }, __slots)?
        };
        let __node_11 = {
            let mut __slots = Slots::new();
            let mut __children: Vec<Box<dyn LayoutItem>> = Vec::new();
            let __node_12 = {
                let mut __slots = Slots::new();
                let mut __children: Vec<Box<dyn LayoutItem>> = Vec::new();
                let __node_13 = {
                    let __sbox_11 = {
                        StyledContainer::new(LayoutStyle::new().flex_column().height(40.0), move |_| RectStyle::default().with_fill(use_theme::<core::theme::SandboxTheme>().success()).with_radius(BorderRadius::all(6.0)), children![])?
                    };
                    let __sbox_12 = {
                        StyledContainer::new(LayoutStyle::new().flex_column().height(40.0), move |_| RectStyle::default().with_fill(use_theme::<core::theme::SandboxTheme>().success()).with_radius(BorderRadius::all(6.0)), children![])?
                    };
                    let __sbox_13 = {
                        StyledContainer::new(LayoutStyle::new().flex_column().height(40.0), move |_| RectStyle::default().with_fill(use_theme::<core::theme::SandboxTheme>().success()).with_radius(BorderRadius::all(6.0)), children![])?
                    };
                    Container::new(LayoutStyle::new().display_grid().grid_template_columns(vec![TemplateTrack::fr(1.0), TemplateTrack::fr(2.0), TemplateTrack::fr(1.0)]).gap(10.0), children![__sbox_11, __sbox_12, __sbox_13])?
                };
                __children.push(box_item(__node_13));
                __slots.extend_default(__children);
                card(CardProps { ..Default::default() }, __slots)?
            };
            __children.push(box_item(__node_12));
            let __node_14 = code_line(CodeLineProps { code: "grid cols:'1fr 2fr 1fr' gap:10" })?;
            __children.push(box_item(__node_14));
            __slots.extend_default(__children);
            example(ExampleProps { title: "Grid — explicit fractional tracks" }, __slots)?
        };
        let __node_15 = {
            let mut __slots = Slots::new();
            let mut __children: Vec<Box<dyn LayoutItem>> = Vec::new();
            let __node_16 = {
                let mut __slots = Slots::new();
                let mut __children: Vec<Box<dyn LayoutItem>> = Vec::new();
                let __node_17 = {
                    let __sbox_14 = {
                        StyledContainer::new(LayoutStyle::new().flex_column().height(40.0), move |_| RectStyle::default().with_fill(use_theme::<core::theme::SandboxTheme>().warning()).with_radius(BorderRadius::all(6.0)), children![])?
                    };
                    let __sbox_15 = {
                        StyledContainer::new(LayoutStyle::new().flex_column().height(40.0), move |_| RectStyle::default().with_fill(use_theme::<core::theme::SandboxTheme>().warning()).with_radius(BorderRadius::all(6.0)), children![])?
                    };
                    let __sbox_16 = {
                        StyledContainer::new(LayoutStyle::new().flex_column().height(40.0), move |_| RectStyle::default().with_fill(use_theme::<core::theme::SandboxTheme>().warning()).with_radius(BorderRadius::all(6.0)), children![])?
                    };
                    let __sbox_17 = {
                        StyledContainer::new(LayoutStyle::new().flex_column().height(40.0), move |_| RectStyle::default().with_fill(use_theme::<core::theme::SandboxTheme>().warning()).with_radius(BorderRadius::all(6.0)), children![])?
                    };
                    let __sbox_18 = {
                        StyledContainer::new(LayoutStyle::new().flex_column().height(40.0), move |_| RectStyle::default().with_fill(use_theme::<core::theme::SandboxTheme>().warning()).with_radius(BorderRadius::all(6.0)), children![])?
                    };
                    Container::new(LayoutStyle::new().display_grid().grid_template_columns(vec![TemplateTrack::fit(TemplateTrack::minmax(TemplateTrack::px(160.0), TemplateTrack::fr(1.0)))]).gap(10.0), children![__sbox_14, __sbox_15, __sbox_16, __sbox_17, __sbox_18])?
                };
                __children.push(box_item(__node_17));
                __slots.extend_default(__children);
                card(CardProps { ..Default::default() }, __slots)?
            };
            __children.push(box_item(__node_16));
            let __node_18 = code_line(CodeLineProps { code: "grid cols:'fit 160'   (auto-fit, minmax(160px, 1fr))" })?;
            __children.push(box_item(__node_18));
            __slots.extend_default(__children);
            example(ExampleProps { title: "Grid — responsive tracks that reflow like wrap but keep their height" }, __slots)?
        };
        let __node_19 = {
            let mut __slots = Slots::new();
            let mut __children: Vec<Box<dyn LayoutItem>> = Vec::new();
            let __col_1 = {
                let __node_20 = prop_row(PropRowProps { name: "width / height", values: "number · N%", about: "Pixels, or a percentage of the parent." })?;
                let __node_21 = prop_row(PropRowProps { name: "min_/max_width", values: "number · N%", about: "Clamp a flexible size." })?;
                let __node_22 = prop_row(PropRowProps { name: "cols", values: "N · tracks · fit/fill N", about: "Turn a grid on: count, explicit tracks, or responsive." })?;
                let __node_23 = prop_row(PropRowProps { name: "span / row_span", values: "number", about: "How many grid tracks a cell covers." })?;
                Container::new(LayoutStyle::new().flex_column().gap(6.0), children![__node_20, __node_21, __node_22, __node_23])?
            };
            __children.push(box_item(__col_1));
            __slots.extend_default(__children);
            example(ExampleProps { title: "Attributes" }, __slots)?
        };
        Container::new(LayoutStyle::new().flex_column().gap(20.0), children![__node_0, __node_1, __node_4, __node_7, __node_11, __node_15, __node_19])?
    };
    Ok(Box::new(__col_0))
}
