// Generated by telar-transpiler — do not edit manually
#![allow(clippy::all)]
#[allow(unused_imports)] use telar::*;
#[allow(unused_imports)] use super::*;

#[derive(::telar::Props)]
pub struct FeaturesSteppersProps {}

#[allow(dead_code, unused_variables, unused_mut)]
pub fn features_steppers(props: FeaturesSteppersProps, children: Children) -> Result<Box<dyn LayoutItem>, LayoutError> {
    let __owner = telar::owner_scope();
    #[allow(unused_imports)] use telar::use_theme;
    let qty = signal(1.0f32);
    let seats = signal(2.0f32);
    // Written by `on_change` rather than read from the bound signal, so the callback is what proves it fired.
    let last_change = signal("no change yet".to_string());

    let __col_0 = {
        let __node_0 = doc_header(DocHeaderProps::props().kicker("INTERACTION").title("Stepper").desc("stepper is a numeric input with − / + buttons that step a bound value within min/max. A component built on the button primitive; the value reads back in your own range, no memo needed.").build(), Children::default())?;
        let __node_1 = {
            let __deferred = Children::new(
                {
                    let qty = qty.clone();
                move || {
                    let qty = qty.clone();
                    let mut __slots = Slots::new();
                    let mut __children: Vec<Box<dyn LayoutItem>> = Vec::new();
                    let __node_2 = {
                        let __deferred = Children::new(
                            {
                                let qty = qty.clone();
                            move || {
                                let qty = qty.clone();
                                let mut __slots = Slots::new();
                                let mut __children: Vec<Box<dyn LayoutItem>> = Vec::new();
                                let __row_0 = {
                                    let __node_3 = stepper(StepperProps::props().value(qty.clone()).min(0.0).max(10.0).step(1.0).build(), Children::default())?;
                                    let __text_0 = {
                                        let qty = qty.clone();
                                        Text::declaring(
                                            move || format!("qty · {}", { qty.get() }),
                                            LayoutStyle::new(),
                                            move |__inherited: TextStyle| __inherited.with_font_size(14.0).with_color(use_theme::<core::theme::SandboxTheme>().muted()),
                                        )?
                                    };
                                    Container::new(LayoutStyle::new().flex_row().gap(16.0).align_items(AlignItems::CENTER), children![__node_3, __text_0])?
                                };
                                __children.push(box_item(__row_0));
                                __slots.extend_default(__children);
                                Ok(__slots)
                            }
                            }
                        );
                        card(CardProps::props().gap(10.0).build(), __deferred)?
                    };
                    __children.push(box_item(__node_2));
                    let __node_4 = code_line(CodeLineProps::props().code("stepper value:$qty min:0 max:10 step:1").build(), Children::default())?;
                    __children.push(box_item(__node_4));
                    __slots.extend_default(__children);
                    Ok(__slots)
                }
                }
            );
            example(ExampleProps::props().title("stepper — bound value, clamped to min/max, stepped by step").build(), __deferred)?
        };
        let __node_5 = {
            let __deferred = Children::new(
                {
                    let seats = seats.clone();
                    let last_change = last_change.clone();
                move || {
                    let seats = seats.clone();
                    let last_change = last_change.clone();
                    let mut __slots = Slots::new();
                    let mut __children: Vec<Box<dyn LayoutItem>> = Vec::new();
                    let __node_6 = {
                        let __deferred = Children::new(
                            {
                                let seats = seats.clone();
                                let last_change = last_change.clone();
                            move || {
                                let seats = seats.clone();
                                let last_change = last_change.clone();
                                let mut __slots = Slots::new();
                                let mut __children: Vec<Box<dyn LayoutItem>> = Vec::new();
                                let __row_1 = {
                                    let __node_7 = stepper(StepperProps::props().value(seats.clone()).min(1.0).max(8.0).step(1.0).on_change(Box::new({ let last_change = last_change.clone(); move |v| last_change.set(format!("stepped to {v:.0}")) })).build(), Children::default())?;
                                    let __text_1 = {
                                        let last_change = last_change.clone();
                                        Text::declaring(
                                            move || format!("{}", { last_change.get() }),
                                            LayoutStyle::new(),
                                            move |__inherited: TextStyle| __inherited.with_font_size(14.0).with_color(use_theme::<core::theme::SandboxTheme>().muted()),
                                        )?
                                    };
                                    Container::new(LayoutStyle::new().flex_row().gap(16.0).align_items(AlignItems::CENTER), children![__node_7, __text_1])?
                                };
                                __children.push(box_item(__row_1));
                                __slots.extend_default(__children);
                                Ok(__slots)
                            }
                            }
                        );
                        card(CardProps::props().gap(10.0).build(), __deferred)?
                    };
                    __children.push(box_item(__node_6));
                    let __node_8 = code_line(CodeLineProps::props().code("stepper value:$seats on_change:|v| $last_change.set(…)   (the binding still updates on its own)").build(), Children::default())?;
                    __children.push(box_item(__node_8));
                    __slots.extend_default(__children);
                    Ok(__slots)
                }
                }
            );
            example(ExampleProps::props().title("on_change — a callback beside the binding, for the work a tap has to trigger").build(), __deferred)?
        };
        let __node_9 = {
            let __deferred = Children::new(
                move || {
                    let mut __slots = Slots::new();
                    let mut __children: Vec<Box<dyn LayoutItem>> = Vec::new();
                    let __col_1 = {
                        let __node_10 = prop_row(PropRowProps::props().name("value").values("signal").about("the bound number, reactive.").build(), Children::default())?;
                        let __node_11 = prop_row(PropRowProps::props().name("min / max").values("number").about("clamp range; an unset max is unbounded.").build(), Children::default())?;
                        let __node_12 = prop_row(PropRowProps::props().name("step").values("number").about("increment per − / + tap (default 1).").build(), Children::default())?;
                        let __node_13 = prop_row(PropRowProps::props().name("on_change").values("closure").about("fires with the new value on each tap.").build(), Children::default())?;
                        Container::new(LayoutStyle::new().flex_column().gap(6.0), children![__node_10, __node_11, __node_12, __node_13])?
                    };
                    __children.push(box_item(__col_1));
                    __slots.extend_default(__children);
                    Ok(__slots)
                }
            );
            example(ExampleProps::props().title("Attributes").build(), __deferred)?
        };
        Container::new(LayoutStyle::new().flex_column().gap(20.0), children![__node_0, __node_1, __node_5, __node_9])?
    };
    Ok(Box::new(__col_0))
}
