// Generated by telar-transpiler — do not edit manually
#![allow(clippy::all)]
#[allow(unused_imports)] use telar::*;
#[allow(unused_imports)] use crate::*;
#[allow(unused_imports)] use crate::shared::components::card::{card, CardProps};
#[allow(unused_imports)] use crate::shared::components::code_line::{code_line, CodeLineProps};
#[allow(unused_imports)] use crate::shared::components::doc_header::{doc_header, DocHeaderProps};
#[allow(unused_imports)] use crate::shared::components::example::{example, ExampleProps};
#[allow(unused_imports)] use crate::shared::components::prop_row::{prop_row, PropRowProps};
#[allow(unused_imports)] use std::sync::Arc;

#[derive(::telar::Props)]
pub struct FeaturesTransformsProps {}

#[allow(dead_code, unused_variables, unused_mut)]
pub fn features_transforms(props: FeaturesTransformsProps, children: Children) -> Result<Box<dyn LayoutItem>, LayoutError> {
    let __owner = telar::owner_scope();
    #[allow(unused_imports)] use telar::use_theme;
    #[allow(unused_variables)] let theme = telar::Theme::<core::theme::SandboxTheme>::default();

    fn arrow(cx: f32, cy: f32, size: f32) -> PathData {
        let hs = size * 0.5;
        let head = size * 0.35;
        let sh = size * 0.18;
        PathData::new()
            .move_to(Point::new(cx - hs, cy - sh))
            .line_to(Point::new(cx + hs - head, cy - sh))
            .line_to(Point::new(cx + hs - head, cy - hs * 0.5))
            .line_to(Point::new(cx + hs, cy))
            .line_to(Point::new(cx + hs - head, cy + hs * 0.5))
            .line_to(Point::new(cx + hs - head, cy + sh))
            .line_to(Point::new(cx - hs, cy + sh))
            .close()
    }

    // Widest x reached by the fixed-coordinate cells below; the drawing is scaled to fit narrower canvases.
    const TRANSFORMS_DESIGN_W: f32 = 640.0;

    fn draw_transforms(rect: Rect) -> RenderNode {
        let t = crate::core::theme::theme();
        let muted = t.muted;
        let palette = [t.primary, t.success, t.warning, t.danger, t.purple];
        let mut kids: Vec<RenderNode> = Vec::new();

        // Uniform scale around each cell's center.
        kids.push(RenderNode::text(
            telar::static_rc_str!("scale around center — 0.5× · 0.75× · 1× · 1.5× · 2×"),
            Rect {
                x: 0.0,
                y: 8.0,
                width: 640.0,
                height: 14.0,
            },
            TextStyle::new(11.0, muted),
        ));
        let scales = [0.5f32, 0.75, 1.0, 1.5, 2.0];
        for (i, (&s, &color)) in scales.iter().zip(palette.iter()).enumerate() {
            let cx = i as f32 * 130.0 + 40.0;
            let cy = 70.0f32;
            let m = Transform::scale_around(s, s, cx, cy).to_array();
            kids.push(RenderNode::transform_with(
                m,
                [RenderNode::rect(
                    Rect {
                        x: cx - 26.0,
                        y: cy - 26.0,
                        width: 52.0,
                        height: 52.0,
                    },
                    RectStyle::filled(color, 6.0),
                )],
            ));
        }

        // Rotation of a shared arrow shape.
        kids.push(RenderNode::text(
            telar::static_rc_str!("rotate around center — 0° · 30° · 60° · 90° · 120°"),
            Rect {
                x: 0.0,
                y: 140.0,
                width: 640.0,
                height: 14.0,
            },
            TextStyle::new(11.0, muted),
        ));
        let angles = [0.0f32, 30.0, 60.0, 90.0, 120.0];
        for (i, (&a, &color)) in angles.iter().zip(palette.iter()).enumerate() {
            let cx = i as f32 * 130.0 + 45.0;
            let cy = 200.0f32;
            let m = Transform::rotate_around(a, cx, cy).to_array();
            kids.push(RenderNode::transform_with(
                m,
                [RenderNode::path(
                    Arc::new(arrow(cx, cy, 54.0)),
                    PathStyle::default().with_fill(color),
                )],
            ));
        }

        // Compose: rotate then scale, both around the same center.
        kids.push(RenderNode::text(
            telar::static_rc_str!("compose — rotate then scale (transforms multiply)"),
            Rect {
                x: 0.0,
                y: 270.0,
                width: 640.0,
                height: 14.0,
            },
            TextStyle::new(11.0, muted),
        ));
        let steps = [0.0f32, 20.0, 40.0, 60.0, 80.0];
        for (i, &a) in steps.iter().enumerate() {
            let cx = i as f32 * 130.0 + 40.0;
            let cy = 325.0f32;
            let s = 1.0 - i as f32 * 0.16;
            let m = Transform::rotate_around(a, cx, cy)
                .then(Transform::scale_around(s, s, cx, cy))
                .to_array();
            kids.push(RenderNode::transform_with(
                m,
                [RenderNode::rect(
                    Rect {
                        x: cx - 26.0,
                        y: cy - 26.0,
                        width: 52.0,
                        height: 52.0,
                    },
                    RectStyle::filled(palette[i % palette.len()], 8.0),
                )],
            ));
        }

        let scale = (rect.width / TRANSFORMS_DESIGN_W).min(1.0);
        RenderNode::transform_with([scale, 0.0, 0.0, scale, 0.0, 0.0], kids)
    }

    let __col_0 = {
        let __node_0 = doc_header(DocHeaderProps::props().kicker("MEDIA").title("Transforms").desc("Wrap any render node in an affine matrix to scale, rotate, or translate it. Transforms compose with .then(), so you can rotate and then scale around the same point.").build(), Children::default())?;
        let __node_1 = {
            let __deferred = Children::new(
                move || {
                    let mut __slots = Slots::new();
                    let mut __children: Vec<Box<dyn LayoutItem>> = Vec::new();
                    let __node_2 = {
                        let __deferred = Children::new(
                            move || {
                                let mut __slots = Slots::new();
                                let mut __children: Vec<Box<dyn LayoutItem>> = Vec::new();
                                let __canvas_0 = Canvas::new(LayoutStyle::new().height(360.0), draw_transforms)?;
                                __children.push(box_item(__canvas_0));
                                __slots.extend_default(__children);
                                Ok(__slots)
                            }
                        );
                        card(CardProps::props().build(), __deferred)?
                    };
                    __children.push(box_item(__node_2));
                    let __node_3 = code_line(CodeLineProps::props().code("Transform::rotate_around(a, cx, cy).then(Transform::scale_around(s, s, cx, cy))").build(), Children::default())?;
                    __children.push(box_item(__node_3));
                    __slots.extend_default(__children);
                    Ok(__slots)
                }
            );
            example(ExampleProps::props().title("Scale, rotate, and a composed rotate-then-scale").build(), __deferred)?
        };
        let __node_4 = {
            let __deferred = Children::new(
                {
                    let theme = theme.clone();
                move || {
                    let theme = theme.clone();
                    let mut __slots = Slots::new();
                    let mut __children: Vec<Box<dyn LayoutItem>> = Vec::new();
                    let __node_5 = {
                        let __deferred = Children::new(
                            {
                                let theme = theme.clone();
                            move || {
                                let theme = theme.clone();
                                let mut __slots = Slots::new();
                                let mut __children: Vec<Box<dyn LayoutItem>> = Vec::new();
                                let __row_0 = {
                                    let __sbox_0 = {
                                        StyledContainer::new(LayoutStyle::new().flex_column().width(56.0).height(56.0), { let theme = theme.clone(); move |_| RectStyle::default().with_fill(theme.get().primary).with_radius(BorderRadius::all(8.0)) }, children![])?
                                    };
                                    let __sbox_1 = {
                                        StyledContainer::new(LayoutStyle::new().flex_column().width(56.0).height(56.0), { let theme = theme.clone(); move |_| RectStyle::default().with_fill(theme.get().success).with_radius(BorderRadius::all(8.0)) }, children![])?.with_transform(move |__r: Rect| box_transform(__r, (20) as f32, (1) as f32, (1) as f32, (0) as f32, (0) as f32))
                                    };
                                    let __sbox_2 = {
                                        StyledContainer::new(LayoutStyle::new().flex_column().width(56.0).height(56.0), { let theme = theme.clone(); move |_| RectStyle::default().with_fill(theme.get().warning).with_radius(BorderRadius::all(8.0)) }, children![])?.with_transform(move |__r: Rect| box_transform(__r, (0) as f32, (1.3) as f32, (1.3) as f32, (0) as f32, (0) as f32))
                                    };
                                    let __sbox_3 = {
                                        StyledContainer::new(LayoutStyle::new().flex_column().width(56.0).height(56.0), { let theme = theme.clone(); move |_| RectStyle::default().with_fill(theme.get().danger).with_radius(BorderRadius::all(8.0)) }, children![])?.with_transform(move |__r: Rect| box_transform(__r, (15) as f32, (0.85) as f32, (0.85) as f32, (0) as f32, (0) as f32))
                                    };
                                    let __sbox_4 = {
                                        StyledContainer::new(LayoutStyle::new().flex_column().width(56.0).height(56.0), { let theme = theme.clone(); move |_| RectStyle::default().with_fill(theme.get().ink).with_radius(BorderRadius::all(8.0)) }, children![])?.with_transform(move |__r: Rect| box_transform(__r, (-12) as f32, (1) as f32, (1) as f32, (0) as f32, (-8) as f32))
                                    };
                                    Container::new(LayoutStyle::new().flex_row().gap(24.0).justify_content(JustifyContent::CENTER).padding_vertical(16.0), children![__sbox_0, __sbox_1, __sbox_2, __sbox_3, __sbox_4])?
                                };
                                __children.push(box_item(__row_0));
                                __slots.extend_default(__children);
                                Ok(__slots)
                            }
                            }
                        );
                        card(CardProps::props().build(), __deferred)?
                    };
                    __children.push(box_item(__node_5));
                    let __node_6 = code_line(CodeLineProps::props().code("box fill:$theme.success rotate:20      box fill:$theme.danger rotate:15 scale:0.85").build(), Children::default())?;
                    __children.push(box_item(__node_6));
                    __slots.extend_default(__children);
                    Ok(__slots)
                }
                }
            );
            example(ExampleProps::props().title("Declarative — rotate / scale / translate as box attributes (no Canvas, no Rust)").build(), __deferred)?
        };
        let __node_7 = {
            let __deferred = Children::new(
                move || {
                    let mut __slots = Slots::new();
                    let mut __children: Vec<Box<dyn LayoutItem>> = Vec::new();
                    let __col_1 = {
                        let __node_8 = prop_row(PropRowProps::props().name("scale_around").values("sx, sy, cx, cy").about("Scale about a pivot point.").build(), Children::default())?;
                        let __node_9 = prop_row(PropRowProps::props().name("rotate_around").values("deg, cx, cy").about("Rotate about a pivot point.").build(), Children::default())?;
                        let __node_10 = prop_row(PropRowProps::props().name(".then(other)").values("Transform").about("Compose two transforms into one matrix.").build(), Children::default())?;
                        let __node_11 = prop_row(PropRowProps::props().name("transform_with").values("matrix, [nodes]").about("Apply a matrix to child render nodes.").build(), Children::default())?;
                        Container::new(LayoutStyle::new().flex_column().gap(6.0), children![__node_8, __node_9, __node_10, __node_11])?
                    };
                    __children.push(box_item(__col_1));
                    __slots.extend_default(__children);
                    Ok(__slots)
                }
            );
            example(ExampleProps::props().title("The Transform API").build(), __deferred)?
        };
        Container::new(LayoutStyle::new().flex_column().gap(20.0), children![__node_0, __node_1, __node_4, __node_7])?
    };
    Ok(Box::new(__col_0))
}
