[package]
name = "renderer-core"
version = "0.1.0"
edition = "2024"

[dependencies]
bytemuck = { workspace = true }
geometry-core = { workspace = true }
resvg = { version = "0.47", optional = true }
rustc-hash = { workspace = true }
smallvec = { workspace = true }
thiserror = { workspace = true }
usvg = { version = "0.47", optional = true }
wide = { workspace = true }

[dev-dependencies]
criterion = "0.8.2"

[[bench]]
name = "scale_commands"
harness = false

[features]
svg = ["dep:usvg", "dep:resvg"]
