[package]
name = "renderer-software"
version = "0.1.0"
edition = "2024"

[dependencies]
renderer-core = { workspace = true }
softbuffer = "0.4"
raw-window-handle = { workspace = true }
tiny-skia = { workspace = true, features = ["simd"] }
renderer-text = { workspace = true }
geometry-core = { workspace = true }
lru = { workspace = true }
rustc-hash = { workspace = true }
clru = { workspace = true }
wide = { workspace = true }
rayon = "1"
smallvec = { workspace = true }
tracing.workspace = true

[target.'cfg(target_os = "android")'.dependencies]
ndk = { version = "0.9", features = ["nativewindow"] }

[target.'cfg(target_os = "linux")'.dependencies]
memmap2 = "0.9"
rustix = { version = "0.38", features = ["fs"] }
wayland-client = "0.31"

[dev-dependencies]
criterion = "0.8.2"
geometry-core = { workspace = true }
image = { version = "0.25.10", default-features = false, features = ["png"] }
layout-core = { workspace = true }
platform-core = { workspace = true }
platform-headless = { workspace = true }
reactive-core = { workspace = true }
ui-components = { workspace = true }
ui-core = { workspace = true }
ui-tree = { workspace = true }

[[bench]]
name = "render_frame"
harness = false
