[package]
name = "renderer-software"
version = "0.1.0"
edition = "2024"

[dependencies]
renderer-core = { workspace = true }
softbuffer = "0.4"
raw-window-handle = { workspace = true }
tiny-skia = { version = "0.12.0", features = ["simd"] }
renderer-text = { workspace = true }
geometry-core = { workspace = true }
arrayvec = { version = "0.7.6", default-features = false }
lru = "0.18.0"
bytemuck = { workspace = true }
rustc-hash = { workspace = true }
clru = { workspace = true }
wide = { workspace = true }
rayon = "1"
smallvec = { version = "1.15.1", features = ["union"] }
