[workspace]
resolver = "3"
members = [
    "crates/platform/platform-core",
    "crates/platform/platform-winit",
    "crates/renderer/renderer-core",
    "crates/renderer/renderer-software",
    "crates/renderer/renderer-hardware",
    "crates/renderer/renderer-text",
    "crates/reactive/reactive-core",
    "crates/services/services-core",
    "crates/geometry/geometry-core",
    "crates/layout/layout-core",
    "crates/ui/ui-core",
    "crates/ui/ui-tree",
    "crates/rsx",
    "crates/tools/cargo-rsx",
    "crates/tools/rsx-parser",
    "crates/tools/rsx-transpiler",
    "crates/tools/rsx-bundler",
    "apps/sandbox",
]

[profile.dev.package."*"]
opt-level = 3

[workspace.dependencies]
thiserror = "2"
raw-window-handle = "0.6"
serde = { version = "1.0.228", features = ["derive"] }
toml = "1.1.2"
tracing = "0.1.44"

platform-core = { path = "crates/platform/platform-core" }
platform-winit = { path = "crates/platform/platform-winit" }
renderer-core = { path = "crates/renderer/renderer-core" }
renderer-software = { path = "crates/renderer/renderer-software" }
renderer-hardware = { path = "crates/renderer/renderer-hardware" }
renderer-text = { path = "crates/renderer/renderer-text" }
reactive-core = { path = "crates/reactive/reactive-core" }
services-core = { path = "crates/services/services-core" }
geometry-core = { path = "crates/geometry/geometry-core" }
layout-core = { path = "crates/layout/layout-core" }
ui-core = { path = "crates/ui/ui-core" }
ui-tree = { path = "crates/ui/ui-tree" }
rsx = { path = "crates/rsx" }
