// Generated by telar-transpiler — do not edit manually
#![allow(clippy::all)]
#[allow(unused_imports)] use telar::*;
#[allow(unused_imports)] use super::*;
#[allow(unused_imports)] use crate::core::theme::theme;

#[allow(dead_code, unused_variables, unused_mut)]
pub fn core_sidebar() -> Result<Box<dyn LayoutItem>, LayoutError> {
    let __owner = telar::owner_scope();
    #[allow(unused_imports)] use telar::use_theme;

    // Reads through use_theme, so switching the theme re-runs this memo and updates the "Active" label.
    let theme_name = memo(move || theme().name.to_string());

    let __col_0 = {
        let __col_1 = {
            let __text_0 = {
                Text::declaring(
                    || "▲ rsx".to_string(),
                    LayoutStyle::new(),
                    move |__inherited: TextStyle| __inherited.with_font_size(20.0).with_color(use_theme::<core::theme::SandboxTheme>().ink()),
                )?
            };
            let __text_1 = {
                Text::declaring(
                    || "Feature gallery".to_string(),
                    LayoutStyle::new(),
                    move |__inherited: TextStyle| __inherited.with_font_size(12.0).with_color(use_theme::<core::theme::SandboxTheme>().muted()),
                )?
            };
            Container::new(LayoutStyle::new().flex_column().gap(2.0), children![__text_0, __text_1])?
        };
        let __col_2 = {
            let __text_2 = {
                Text::declaring(
                    || "THEME".to_string(),
                    LayoutStyle::new(),
                    move |__inherited: TextStyle| __inherited.with_font_size(11.0).with_color(use_theme::<core::theme::SandboxTheme>().muted()),
                )?
            };
            let __col_3 = {
                let __row_0 = {
                    let __node_0 = button(ButtonProps { label: Box::new(move || "Modern".to_string()), fill: Box::new(move || use_theme::<core::theme::SandboxTheme>().primary()), on_press: Box::new(move || set_mode("modern")), ..Default::default() })?;
                    let __node_1 = button(ButtonProps { label: Box::new(move || "Pastel".to_string()), fill: Box::new(move || use_theme::<core::theme::SandboxTheme>().primary()), on_press: Box::new(move || set_mode("pastel")), ..Default::default() })?;
                    let __node_2 = button(ButtonProps { label: Box::new(move || "Midnight".to_string()), fill: Box::new(move || use_theme::<core::theme::SandboxTheme>().primary()), on_press: Box::new(move || set_mode("midnight")), ..Default::default() })?;
                    Container::new(LayoutStyle::new().flex_row().gap(6.0).flex_wrap(), children![__node_0, __node_1, __node_2])?
                };
                let __text_3 = {
                    let theme_name = theme_name.clone();
                    Text::declaring(
                        move || format!("Active · {}", { theme_name.get() }),
                        LayoutStyle::new(),
                        move |__inherited: TextStyle| __inherited.with_font_size(12.0).with_color(use_theme::<core::theme::SandboxTheme>().muted()),
                    )?
                };
                Container::new(LayoutStyle::new().flex_column().gap(6.0), children![__row_0, __text_3])?
            };
            Container::new(LayoutStyle::new().flex_column().gap(8.0), children![__text_2, __col_3])?
        };
        Container::new(LayoutStyle::new().flex_column().gap(22.0), children![__col_1, __col_2])?
    };
    Ok(Box::new(__col_0))
}
