//! RSX transpiler: converts a parsed [`RsxDocument`] AST into compilable Rust
//! source code that depends on `rsx::*`.

mod error;
mod naming;
mod preview_scan;
mod signal_scan;
mod style;
mod view;

pub use error::TranspileError;

use rsx_parser::RsxDocument;

use crate::naming::{mentions_ident, replace_whole_word, to_snake_case};
use crate::preview_scan::scan_previews;
use crate::signal_scan::scan_signals;
use crate::style::generate_style_section;
use crate::view::ViewGen;

/// Input to a single transpilation: the parsed document plus the desired
/// component function name (typically derived from the source file stem).
pub struct TranspileInput<'a> {
    pub document: &'a RsxDocument,
    pub component_name: &'a str,
}

/// The generated Rust source for one `.rsx` file.
pub struct TranspiledSource {
    pub rust_code: String,
    pub preview_names: Vec<String>,
}

/// Transpiles `source` directly: parses it, then generates Rust for `component_name`.
pub fn transpile_source(
    source: &str,
    component_name: &str,
) -> Result<TranspiledSource, TranspileError> {
    let document = rsx_parser::parse(source)?;
    transpile(TranspileInput {
        document: &document,
        component_name,
    })
}

/// Transpiles a parsed document into Rust source.
pub fn transpile(input: TranspileInput<'_>) -> Result<TranspiledSource, TranspileError> {
    let doc = input.document;
    let fn_name = to_snake_case(input.component_name);
    if fn_name.is_empty() {
        return Err(TranspileError::Codegen(
            "component name is empty or has no valid identifier characters".into(),
        ));
    }

    let signals = scan_signals(&doc.logic.source);
    let previews = scan_previews(&doc.logic.source);
    let has_props = detect_props(&doc.logic.source);

    let style_section = generate_style_section(&doc.style);

    let mut view_gen = ViewGen::new(&signals, &doc.style.classes, &doc.style.constants);
    let view_body = view_gen.generate_root(&doc.view.nodes);

    let logic = doc.logic.source.trim_end();

    let signature = if has_props {
        format!(
            "pub fn {fn_name}(ctx: &mut WidgetCtx, props: Props) -> Result<Box<dyn LayoutItem>, LayoutError>"
        )
    } else {
        format!("pub fn {fn_name}(ctx: &mut WidgetCtx) -> Result<Box<dyn LayoutItem>, LayoutError>")
    };

    let mut out = String::new();
    out.push_str("// Generated by rsx-transpiler — do not edit manually\n");
    // Outer attribute on use so this file is safe to include! from another crate.
    out.push_str("#[allow(unused_imports)] use rsx::*;\n\n");

    if !style_section.is_empty() {
        out.push_str(&style_section);
        if !style_section.ends_with('\n') {
            out.push('\n');
        }
        out.push('\n');
    }

    out.push_str("#[allow(dead_code, unused_variables, unused_mut)]\n");
    out.push_str(&signature);
    out.push_str(" {\n");

    if !logic.is_empty() {
        // Track which signals have been declared so far in the logic zone.
        let mut declared: Vec<&str> = Vec::new();
        for line in logic.lines() {
            if line.is_empty() {
                out.push('\n');
                continue;
            }
            // Preview attributes are metadata for the bundler, not Rust code; strip them.
            if line.trim().starts_with("#[preview(") {
                continue;
            }
            // If this line has a `move` closure that captures a previously declared
            // signal, emit a dedicated clone with a mangled name for the closure,
            // then rewrite the line so the closure captures that clone instead of
            // the original. This leaves the original binding intact for the view code.
            let mut emitted_line = line.to_string();
            if line.contains("move") {
                for sig_name in &declared {
                    if mentions_ident(line, sig_name) {
                        let mv_name = format!("{sig_name}_rsx_mv");
                        out.push_str(&format!("    let {mv_name} = {sig_name}.clone();\n"));
                        // Replace the signal name inside the closure with the mangled name.
                        emitted_line = replace_whole_word(&emitted_line, sig_name, &mv_name);
                    }
                }
            }
            out.push_str("    ");
            out.push_str(&emitted_line);
            out.push('\n');
            // After emitting, record any signal declared on this line.
            for sig in &signals {
                let decl_prefix = format!("let {} =", sig.name);
                let decl_prefix_mut = format!("let mut {} =", sig.name);
                if line.trim_start().starts_with(&decl_prefix)
                    || line.trim_start().starts_with(&decl_prefix_mut)
                {
                    declared.push(&sig.name);
                }
            }
        }
        out.push('\n');
    }

    out.push_str(&view_body);
    if !out.ends_with('\n') {
        out.push('\n');
    }
    out.push_str("}\n");

    if !previews.is_empty() {
        out.push('\n');
        let const_name = format!(
            "{}_PREVIEW_ENTRIES",
            fn_name.to_uppercase().replace('-', "_")
        );
        out.push_str(&format!(
            "pub const {const_name}: &[::rsx::PreviewEntry] = &[\n"
        ));
        for preview in &previews {
            out.push_str(&format!(
                "    ::rsx::PreviewEntry {{ component_name: \"{fn_name}\", preview_name: \"{}\", build: {fn_name} }},\n",
                preview.name.replace('"', "\\\"")
            ));
        }
        out.push_str("];\n");
    }

    Ok(TranspiledSource {
        rust_code: out,
        preview_names: previews.iter().map(|p| p.name.clone()).collect(),
    })
}

/// Detects whether the logic zone declares a `Props` struct (positional or derived).
fn detect_props(logic: &str) -> bool {
    logic.contains("struct Props") || logic.contains("derive(Props)")
}

#[cfg(test)]
mod tests {
    use super::*;

    const COUNTER: &str = r#"let count = create_rw_signal(0i32);

[style]
primary: #3d78fa
dark: #141424

.card
    width: 240
    padding: 20
    gap: 12
    direction: col
    align: center

[view]
col .card
    text "Count: {count}" size:14 color:dark
    btn "Increment" fill:primary on_press:|| count.update(|n| *n += 1)
"#;

    #[test]
    fn generates_counter() {
        let out = transpile_source(COUNTER, "counter").unwrap();
        let code = out.rust_code;
        assert!(code.contains("pub fn counter(ctx: &mut WidgetCtx)"));
        assert!(code.contains("const COLOR_PRIMARY: Color = Color::rgba(61.0 / 255.0"));
        assert!(code.contains("fn style_card() -> LayoutStyle"));
        assert!(code.contains("move || format!(\"Count: {}\", count.get())"));
        assert!(code.contains("Button::new(ctx, \"Increment\")?"));
        assert!(code.contains(".on_click(move || count.update(|n| *n += 1))"));
        assert!(code.contains("Container::new(ctx, style_card(), children!["));
        assert!(code.contains("Ok(Box::new(__w"));
    }

    #[test]
    fn detects_props_signature() {
        let src =
            "#[derive(Props)]\npub struct Props { pub title: &'static str }\n[view]\ntext \"hi\"\n";
        let out = transpile_source(src, "card").unwrap();
        assert!(
            out.rust_code
                .contains("pub fn card(ctx: &mut WidgetCtx, props: Props)")
        );
    }
}
