[package]
name = "ui-core"
version = "0.1.0"
edition = "2024"

[dependencies]
geometry-core = { workspace = true }
layout-core = { workspace = true }
layout-reactive = { workspace = true }
platform-core = { workspace = true }
reactive-core = { workspace = true }
renderer-core = { workspace = true }
renderer-text = { workspace = true }
theme-core = { workspace = true }
ui-tree = { workspace = true }

[features]
svg = ["renderer-core/svg"]
