[package]
name = "rsx-analyzer"
version = "0.1.0"
edition = "2024"

[dependencies]
rsx-parser = { workspace = true }
rsx-workspace = { workspace = true }
rsx-transpiler = { workspace = true }
serde = { workspace = true }
toml = { workspace = true }
lsp-types = "0.97"
serde_json = "1"
tokio = { version = "1", features = [
    "rt",
    "macros",
    "io-std",
    "io-util",
    "sync",
    "time",
] }
url = "2.5.8"
rsx-diagnostics = { workspace = true, features = ["lsp"] }
ra_ap_ide = "=0.0.338"
ra_ap_ide_db = "=0.0.338"
ra_ap_load-cargo = "=0.0.338"
ra_ap_project_model = "=0.0.338"
ra_ap_vfs = "=0.0.338"
ra_ap_paths = "=0.0.338"
anyhow = "1.0.103"
ra_ap_proc_macro_api = "=0.0.338"
