[package]
name = "cargo-telar"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Cargo subcommand for Telar apps: dev server with hot reload, and packaging into native installers."
keywords = ["telar", "cargo", "cli", "gui", "hot-reload"]
categories = ["development-tools::cargo-plugins", "command-line-utilities", "gui"]
readme.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
serde = { workspace = true }
toml = { workspace = true }
telar = { path = "../../telar", version = "0.1.2", default-features = false }
notify = "8.2.0"
clap = { version = "4.6.1", features = ["derive"] }
telar-workspace = { workspace = true }
telar-parser = { workspace = true }
serde_json = "1.0.151"
