[package]
name = "cargo-telar"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { workspace = true }
toml = { workspace = true }
telar = { path = "../../telar", default-features = false }
notify = "8.2.0"
clap = { version = "4.6.1", features = ["derive"] }
telar-workspace = { workspace = true }
