// Generated by telar-transpiler — do not edit manually
#![allow(clippy::all)]
#![allow(noop_method_call)]
#[allow(unused_imports)] use telar::*;
#[allow(unused_imports)] use crate::*;
#[allow(unused_imports)] use crate::feature_card::{feature_card, FeatureCardProps};
#[allow(unused_imports)] use crate::demo_images::{make_checker, make_gradient, make_radial_alpha};
#[allow(unused_imports)] use std::sync::Arc;

#[derive(::telar::Props)]
pub struct HomeProps {}

#[allow(dead_code)]
fn style_page() -> LayoutStyle {
    #[allow(unused_variables)] let theme = telar::Theme::<theme::LandingTheme>::default();
    LayoutStyle::new()
        .flex_column()
}

#[allow(dead_code)]
fn style_navband() -> LayoutStyle {
    #[allow(unused_variables)] let theme = telar::Theme::<theme::LandingTheme>::default();
    LayoutStyle::new()
        .flex_column()
        .align_items(AlignItems::CENTER)
        .padding_horizontal(24.0)
        .padding_vertical(14.0)
}

#[allow(dead_code)]
fn style_footband() -> LayoutStyle {
    #[allow(unused_variables)] let theme = telar::Theme::<theme::LandingTheme>::default();
    LayoutStyle::new()
        .flex_column()
        .align_items(AlignItems::CENTER)
        .padding_horizontal(24.0)
        .padding_vertical(40.0)
}

#[allow(dead_code)]
fn style_band() -> LayoutStyle {
    #[allow(unused_variables)] let theme = telar::Theme::<theme::LandingTheme>::default();
    LayoutStyle::new()
        .flex_column()
        .align_items(AlignItems::CENTER)
        .padding_horizontal(24.0)
        .padding_vertical(64.0)
}

#[allow(dead_code)]
fn style_wrap() -> LayoutStyle {
    #[allow(unused_variables)] let theme = telar::Theme::<theme::LandingTheme>::default();
    LayoutStyle::new()
        .flex_column()
        .width(SizeDimension::Percent(1.0))
        .max_width(1120.0)
        .gap(40.0)
}

#[allow(dead_code)]
fn style_navwrap() -> LayoutStyle {
    #[allow(unused_variables)] let theme = telar::Theme::<theme::LandingTheme>::default();
    LayoutStyle::new()
        .flex_row()
        .width(SizeDimension::Percent(1.0))
        .max_width(1120.0)
        .align_items(AlignItems::CENTER)
        .justify_content(JustifyContent::SPACE_BETWEEN)
}

#[allow(dead_code)]
fn style_footwrap() -> LayoutStyle {
    #[allow(unused_variables)] let theme = telar::Theme::<theme::LandingTheme>::default();
    LayoutStyle::new()
        .flex_row()
        .width(SizeDimension::Percent(1.0))
        .max_width(1120.0)
        .justify_content(JustifyContent::SPACE_BETWEEN)
        .gap(32.0)
}

#[allow(dead_code, unused_variables, unused_mut)]
pub fn home(props: HomeProps, children: Children) -> Result<Box<dyn LayoutItem>, LayoutError> {
    let __owner = telar::owner_scope();
    #[allow(unused_imports)] use telar::use_theme;
    #[allow(unused_variables)] let theme = telar::Theme::<theme::LandingTheme>::default();

    let signups = signal(0i32);
    let signups_rsx_mv = signups.clone();
    let spots_left = memo(move || (200 - signups_rsx_mv.get()).max(0));
    let gradient_img = Arc::new(make_gradient(640, 400));
    let checker_img = Arc::new(make_checker(640, 400, 32));
    let radial_img = Arc::new(make_radial_alpha(640, 400));

    const PRIMARY: Color = Color::rgba(0.263, 0.380, 0.933, 1.0);

    let __col_0 = {
        let __sbox_0 = {
            let __row_0 = {
                let __text_0 = {
                    Text::declaring(
                        || "▲ rsx".to_string(),
                        LayoutStyle::new(),
                        { let theme = theme.clone(); move |__inherited: TextStyle| __inherited.with_font_size(20.0).with_color(theme.get().dark) },
                    )?
                };
                let __row_1 = {
                    let __text_1 = {
                        Text::declaring(
                            || "Features".to_string(),
                            LayoutStyle::new(),
                            { let theme = theme.clone(); move |__inherited: TextStyle| __inherited.with_font_size(14.0).with_color(theme.get().muted) },
                        )?
                    };
                    let __text_2 = {
                        Text::declaring(
                            || "Gallery".to_string(),
                            LayoutStyle::new(),
                            { let theme = theme.clone(); move |__inherited: TextStyle| __inherited.with_font_size(14.0).with_color(theme.get().muted) },
                        )?
                    };
                    let __text_3 = {
                        Text::declaring(
                            || "Pricing".to_string(),
                            LayoutStyle::new(),
                            { let theme = theme.clone(); move |__inherited: TextStyle| __inherited.with_font_size(14.0).with_color(theme.get().muted) },
                        )?
                    };
                    let __node_0 = button(ButtonProps::props().label("Get started").fill(PRIMARY).on_press(std::rc::Rc::new({ let signups = signups.clone(); move || signups.update(|n| *n += 1) })).build(), Children::default())?;
                    Container::new(LayoutStyle::new().flex_row().gap(24.0).align_items(AlignItems::CENTER), children![__text_1, __text_2, __text_3, __node_0])?
                };
                Container::new(style_navwrap(), children![__text_0, __row_1])?
            };
            StyledContainer::new(style_navband(), { let theme = theme.clone(); move |_| RectStyle::default().with_fill(theme.get().surface).with_radius(BorderRadius::zero()) }, children![__row_0])?
        };
        let __sbox_1 = {
            let __col_1 = {
                let __row_2 = {
                    let __col_2 = {
                        let __text_4 = {
                            Text::declaring(
                                || "Native UIs in Rust, without the boilerplate".to_string(),
                                LayoutStyle::new(),
                                { let theme = theme.clone(); move |__inherited: TextStyle| __inherited.with_font_size(40.0).with_color(theme.get().dark) },
                            )?
                        };
                        let __text_5 = {
                            Text::declaring(
                                || "rsx compiles declarative .rsx markup to GPU-accelerated widgets — signals, layout and theming included, from desktop to Android.".to_string(),
                                LayoutStyle::new(),
                                { let theme = theme.clone(); move |__inherited: TextStyle| __inherited.with_font_size(18.0).with_color(theme.get().muted) },
                            )?
                        };
                        let __row_3 = {
                            let __node_1 = button(ButtonProps::props().label("Get started").fill(PRIMARY).on_press(std::rc::Rc::new({ let signups = signups.clone(); move || signups.update(|n| *n += 1) })).build(), Children::default())?;
                            let __node_2 = button(ButtonProps::props().label("Read the docs").outline(PRIMARY).build(), Children::default())?;
                            Container::new(LayoutStyle::new().flex_row().gap(12.0).flex_wrap(), children![__node_1, __node_2])?
                        };
                        let __text_6 = {
                            let spots_left = spots_left.clone();
                            Text::declaring(
                                move || format!("{} of 200 early-access seats left", { spots_left.get() }),
                                LayoutStyle::new(),
                                { let theme = theme.clone(); move |__inherited: TextStyle| __inherited.with_font_size(13.0).with_color(theme.get().accent) },
                            )?
                        };
                        Container::new(LayoutStyle::new().flex_column().flex_grow(1.0).min_width(320.0).gap(20.0), children![__text_4, __text_5, __row_3, __text_6])?
                    };
                    let __col_3 = {
                        let __img_0 = {
                            let __src = gradient_img.clone();
                            Image::new(
                                LayoutStyle::new().width(SizeDimension::Percent(1.0)).height(320.0),
                                move || __src.clone(),
                                move || Raster::Smooth,
                                move || ObjectFit::Contain,
                            )?
                        };
                        Container::new(LayoutStyle::new().flex_column().flex_grow(1.0).min_width(320.0), children![__img_0])?
                    };
                    Container::new(LayoutStyle::new().flex_row().gap(48.0).flex_wrap().align_items(AlignItems::CENTER), children![__col_2, __col_3])?
                };
                Container::new(style_wrap(), children![__row_2])?
            };
            StyledContainer::new(style_band(), { let theme = theme.clone(); move |_| RectStyle::default().with_fill(theme.get().surface).with_radius(BorderRadius::zero()) }, children![__col_1])?
        };
        let __sbox_2 = {
            let __col_4 = {
                let __text_7 = {
                    Text::declaring(
                        || "Trusted primitives".to_string(),
                        LayoutStyle::new(),
                        { let theme = theme.clone(); move |__inherited: TextStyle| __inherited.with_font_size(14.0).with_color(theme.get().muted) },
                    )?
                };
                let __row_4 = {
                    let __sbox_3 = {
                        let __text_8 = {
                            Text::declaring(
                                || "60 fps".to_string(),
                                LayoutStyle::new(),
                                move |__inherited: TextStyle| __inherited.with_font_size(30.0).with_color(PRIMARY),
                            )?
                        };
                        let __text_9 = {
                            Text::declaring(
                                || "software + wgpu".to_string(),
                                LayoutStyle::new(),
                                { let theme = theme.clone(); move |__inherited: TextStyle| __inherited.with_font_size(13.0).with_color(theme.get().muted) },
                            )?
                        };
                        StyledContainer::new(LayoutStyle::new().flex_column().flex_grow(1.0).min_width(170.0).padding_all(24.0).gap(6.0).flex_column().align_items(AlignItems::CENTER), { let theme = theme.clone(); move |_| RectStyle { fill: Some(Paint::Solid(theme.get().surface)), border: Some(Border { paint: Paint::Solid(theme.get().border), widths: [1.0; 4] }), shadow: None, radius: BorderRadius::all(14.0) } }, children![__text_8, __text_9])?
                    };
                    let __sbox_4 = {
                        let __text_10 = {
                            Text::declaring(
                                || "25".to_string(),
                                LayoutStyle::new(),
                                move |__inherited: TextStyle| __inherited.with_font_size(30.0).with_color(PRIMARY),
                            )?
                        };
                        let __text_11 = {
                            Text::declaring(
                                || "modular crates".to_string(),
                                LayoutStyle::new(),
                                { let theme = theme.clone(); move |__inherited: TextStyle| __inherited.with_font_size(13.0).with_color(theme.get().muted) },
                            )?
                        };
                        StyledContainer::new(LayoutStyle::new().flex_column().flex_grow(1.0).min_width(170.0).padding_all(24.0).gap(6.0).flex_column().align_items(AlignItems::CENTER), { let theme = theme.clone(); move |_| RectStyle { fill: Some(Paint::Solid(theme.get().surface)), border: Some(Border { paint: Paint::Solid(theme.get().border), widths: [1.0; 4] }), shadow: None, radius: BorderRadius::all(14.0) } }, children![__text_10, __text_11])?
                    };
                    let __sbox_5 = {
                        let __text_12 = {
                            Text::declaring(
                                || "2".to_string(),
                                LayoutStyle::new(),
                                move |__inherited: TextStyle| __inherited.with_font_size(30.0).with_color(PRIMARY),
                            )?
                        };
                        let __text_13 = {
                            Text::declaring(
                                || "render backends".to_string(),
                                LayoutStyle::new(),
                                { let theme = theme.clone(); move |__inherited: TextStyle| __inherited.with_font_size(13.0).with_color(theme.get().muted) },
                            )?
                        };
                        StyledContainer::new(LayoutStyle::new().flex_column().flex_grow(1.0).min_width(170.0).padding_all(24.0).gap(6.0).flex_column().align_items(AlignItems::CENTER), { let theme = theme.clone(); move |_| RectStyle { fill: Some(Paint::Solid(theme.get().surface)), border: Some(Border { paint: Paint::Solid(theme.get().border), widths: [1.0; 4] }), shadow: None, radius: BorderRadius::all(14.0) } }, children![__text_12, __text_13])?
                    };
                    let __sbox_6 = {
                        let __text_14 = {
                            Text::declaring(
                                || "0".to_string(),
                                LayoutStyle::new(),
                                move |__inherited: TextStyle| __inherited.with_font_size(30.0).with_color(PRIMARY),
                            )?
                        };
                        let __text_15 = {
                            Text::declaring(
                                || "runtime GC pauses".to_string(),
                                LayoutStyle::new(),
                                { let theme = theme.clone(); move |__inherited: TextStyle| __inherited.with_font_size(13.0).with_color(theme.get().muted) },
                            )?
                        };
                        StyledContainer::new(LayoutStyle::new().flex_column().flex_grow(1.0).min_width(170.0).padding_all(24.0).gap(6.0).flex_column().align_items(AlignItems::CENTER), { let theme = theme.clone(); move |_| RectStyle { fill: Some(Paint::Solid(theme.get().surface)), border: Some(Border { paint: Paint::Solid(theme.get().border), widths: [1.0; 4] }), shadow: None, radius: BorderRadius::all(14.0) } }, children![__text_14, __text_15])?
                    };
                    Container::new(LayoutStyle::new().flex_row().gap(20.0).flex_wrap(), children![__sbox_3, __sbox_4, __sbox_5, __sbox_6])?
                };
                Container::new(style_wrap().gap(24.0), children![__text_7, __row_4])?
            };
            StyledContainer::new(style_band(), { let theme = theme.clone(); move |_| RectStyle::default().with_fill(theme.get().surface_alt).with_radius(BorderRadius::zero()) }, children![__col_4])?
        };
        let __sbox_7 = {
            let __col_5 = {
                let __col_6 = {
                    let __text_16 = {
                        Text::declaring(
                            || "Everything you need".to_string(),
                            LayoutStyle::new(),
                            { let theme = theme.clone(); move |__inherited: TextStyle| __inherited.with_font_size(28.0).with_color(theme.get().dark) },
                        )?
                    };
                    let __text_17 = {
                        Text::declaring(
                            || "Composable building blocks that scale from a button to a full app.".to_string(),
                            LayoutStyle::new(),
                            { let theme = theme.clone(); move |__inherited: TextStyle| __inherited.with_font_size(16.0).with_color(theme.get().muted) },
                        )?
                    };
                    Container::new(LayoutStyle::new().flex_column().gap(8.0), children![__text_16, __text_17])?
                };
                let __row_5 = {
                    let __node_3 = feature_card(FeatureCardProps::props().icon("⚡").title("Fast").body("Software and wgpu renderers with dirty-tracking and scroll-blit detection.").build(), Children::default())?;
                    let __node_4 = feature_card(FeatureCardProps::props().icon("🧩").title("Composable").body("Signals, memos and reusable .rsx components compose right inside the markup.").build(), Children::default())?;
                    let __node_5 = feature_card(FeatureCardProps::props().icon("🎨").title("Themeable").body("Semantic color tokens resolve reactively, so dark mode is a single swap.").build(), Children::default())?;
                    let __node_6 = feature_card(FeatureCardProps::props().icon("📱").title("Cross-platform").body("One codebase targets desktop and Android with native event loops.").build(), Children::default())?;
                    Container::new(LayoutStyle::new().flex_row().gap(24.0).flex_wrap(), children![__node_3, __node_4, __node_5, __node_6])?
                };
                Container::new(style_wrap().gap(28.0), children![__col_6, __row_5])?
            };
            StyledContainer::new(style_band(), { let theme = theme.clone(); move |_| RectStyle::default().with_fill(theme.get().surface).with_radius(BorderRadius::zero()) }, children![__col_5])?
        };
        let __sbox_8 = {
            let __col_7 = {
                let __col_8 = {
                    let __text_18 = {
                        Text::declaring(
                            || "Built-in rendering".to_string(),
                            LayoutStyle::new(),
                            { let theme = theme.clone(); move |__inherited: TextStyle| __inherited.with_font_size(28.0).with_color(theme.get().dark) },
                        )?
                    };
                    let __text_19 = {
                        Text::declaring(
                            || "Gradients, images, paths and shadows — all GPU-accelerated.".to_string(),
                            LayoutStyle::new(),
                            { let theme = theme.clone(); move |__inherited: TextStyle| __inherited.with_font_size(16.0).with_color(theme.get().muted) },
                        )?
                    };
                    Container::new(LayoutStyle::new().flex_column().gap(8.0), children![__text_18, __text_19])?
                };
                let __row_6 = {
                    let __col_9 = {
                        let __img_1 = {
                            let __src = gradient_img.clone();
                            Image::new(
                                LayoutStyle::new().width(SizeDimension::Percent(1.0)).height(200.0),
                                move || __src.clone(),
                                move || Raster::Smooth,
                                move || ObjectFit::Contain,
                            )?
                        };
                        let __text_20 = {
                            Text::declaring(
                                || "Linear gradients".to_string(),
                                LayoutStyle::new(),
                                { let theme = theme.clone(); move |__inherited: TextStyle| __inherited.with_font_size(13.0).with_color(theme.get().muted) },
                            )?
                        };
                        Container::new(LayoutStyle::new().flex_column().flex_grow(1.0).min_width(280.0).gap(8.0), children![__img_1, __text_20])?
                    };
                    let __col_10 = {
                        let __img_2 = {
                            let __src = checker_img.clone();
                            Image::new(
                                LayoutStyle::new().width(SizeDimension::Percent(1.0)).height(200.0),
                                move || __src.clone(),
                                move || Raster::Smooth,
                                move || ObjectFit::Contain,
                            )?
                        };
                        let __text_21 = {
                            Text::declaring(
                                || "Bitmap images".to_string(),
                                LayoutStyle::new(),
                                { let theme = theme.clone(); move |__inherited: TextStyle| __inherited.with_font_size(13.0).with_color(theme.get().muted) },
                            )?
                        };
                        Container::new(LayoutStyle::new().flex_column().flex_grow(1.0).min_width(280.0).gap(8.0), children![__img_2, __text_21])?
                    };
                    let __col_11 = {
                        let __img_3 = {
                            let __src = radial_img.clone();
                            Image::new(
                                LayoutStyle::new().width(SizeDimension::Percent(1.0)).height(200.0),
                                move || __src.clone(),
                                move || Raster::Smooth,
                                move || ObjectFit::Contain,
                            )?
                        };
                        let __text_22 = {
                            Text::declaring(
                                || "Radial alpha".to_string(),
                                LayoutStyle::new(),
                                { let theme = theme.clone(); move |__inherited: TextStyle| __inherited.with_font_size(13.0).with_color(theme.get().muted) },
                            )?
                        };
                        Container::new(LayoutStyle::new().flex_column().flex_grow(1.0).min_width(280.0).gap(8.0), children![__img_3, __text_22])?
                    };
                    Container::new(LayoutStyle::new().flex_row().gap(20.0).flex_wrap(), children![__col_9, __col_10, __col_11])?
                };
                Container::new(style_wrap().gap(28.0), children![__col_8, __row_6])?
            };
            StyledContainer::new(style_band(), { let theme = theme.clone(); move |_| RectStyle::default().with_fill(theme.get().surface_alt).with_radius(BorderRadius::zero()) }, children![__col_7])?
        };
        let __sbox_9 = {
            let __col_12 = {
                let __row_7 = {
                    let __col_13 = {
                        let __img_4 = {
                            let __src = checker_img.clone();
                            Image::new(
                                LayoutStyle::new().width(SizeDimension::Percent(1.0)).height(280.0),
                                move || __src.clone(),
                                move || Raster::Smooth,
                                move || ObjectFit::Contain,
                            )?
                        };
                        Container::new(LayoutStyle::new().flex_column().flex_grow(1.0).min_width(300.0), children![__img_4])?
                    };
                    let __col_14 = {
                        let __text_23 = {
                            Text::declaring(
                                || "Reactivity that stays out of your way".to_string(),
                                LayoutStyle::new(),
                                { let theme = theme.clone(); move |__inherited: TextStyle| __inherited.with_font_size(26.0).with_color(theme.get().dark) },
                            )?
                        };
                        let __text_24 = {
                            Text::declaring(
                                || "Fine-grained signals update only the widgets that depend on them — no virtual DOM, no diffing, no re-render storms.".to_string(),
                                LayoutStyle::new(),
                                { let theme = theme.clone(); move |__inherited: TextStyle| __inherited.with_font_size(16.0).with_color(theme.get().muted) },
                            )?
                        };
                        let __text_25 = {
                            Text::declaring(
                                || "→ signal, memo, effect".to_string(),
                                LayoutStyle::new(),
                                move |__inherited: TextStyle| __inherited.with_font_size(14.0).with_color(PRIMARY),
                            )?
                        };
                        Container::new(LayoutStyle::new().flex_column().flex_grow(1.0).min_width(300.0).gap(14.0), children![__text_23, __text_24, __text_25])?
                    };
                    Container::new(LayoutStyle::new().flex_row().gap(48.0).flex_wrap().align_items(AlignItems::CENTER), children![__col_13, __col_14])?
                };
                Container::new(style_wrap(), children![__row_7])?
            };
            StyledContainer::new(style_band(), { let theme = theme.clone(); move |_| RectStyle::default().with_fill(theme.get().surface).with_radius(BorderRadius::zero()) }, children![__col_12])?
        };
        let __sbox_10 = {
            let __col_15 = {
                let __text_26 = {
                    Text::declaring(
                        || "Join the private beta".to_string(),
                        LayoutStyle::new(),
                        { let theme = theme.clone(); move |__inherited: TextStyle| __inherited.with_font_size(30.0).with_color(theme.get().on_primary) },
                    )?
                };
                let __text_27 = {
                    let spots_left = spots_left.clone();
                    Text::declaring(
                        move || format!("{} of 200 seats remaining", { spots_left.get() }),
                        LayoutStyle::new(),
                        { let theme = theme.clone(); move |__inherited: TextStyle| __inherited.with_font_size(16.0).with_color(theme.get().on_primary) },
                    )?
                };
                let __row_8 = {
                    let __node_7 = button(ButtonProps::props().label("Reserve a seat").fill(Reactive::of({ let theme = theme.clone(); move || theme.get().accent })).on_press(std::rc::Rc::new({ let signups = signups.clone(); move || signups.update(|n| *n += 1) })).build(), Children::default())?;
                    let __text_28 = {
                        let signups = signups.clone();
                        Text::declaring(
                            move || format!("{} developers reserved", { signups.get() }),
                            LayoutStyle::new(),
                            { let theme = theme.clone(); move |__inherited: TextStyle| __inherited.with_font_size(14.0).with_color(theme.get().on_primary) },
                        )?
                    };
                    Container::new(LayoutStyle::new().flex_row().gap(12.0).align_items(AlignItems::CENTER).flex_wrap(), children![__node_7, __text_28])?
                };
                Container::new(style_wrap().align_items(AlignItems::CENTER).gap(16.0), children![__text_26, __text_27, __row_8])?
            };
            StyledContainer::new(style_band(), move |_| RectStyle::default().with_fill(PRIMARY).with_radius(BorderRadius::zero()), children![__col_15])?
        };
        let __sbox_11 = {
            let __row_9 = {
                let __col_16 = {
                    let __text_29 = {
                        Text::declaring(
                            || "▲ rsx".to_string(),
                            LayoutStyle::new(),
                            { let theme = theme.clone(); move |__inherited: TextStyle| __inherited.with_font_size(18.0).with_color(theme.get().on_primary) },
                        )?
                    };
                    let __text_30 = {
                        Text::declaring(
                            || "Native UI framework for Rust.".to_string(),
                            LayoutStyle::new(),
                            { let theme = theme.clone(); move |__inherited: TextStyle| __inherited.with_font_size(13.0).with_color(theme.get().on_dark) },
                        )?
                    };
                    Container::new(LayoutStyle::new().flex_column().gap(8.0).flex_grow(1.0).min_width(200.0), children![__text_29, __text_30])?
                };
                let __col_17 = {
                    let __text_31 = {
                        Text::declaring(
                            || "Product".to_string(),
                            LayoutStyle::new(),
                            { let theme = theme.clone(); move |__inherited: TextStyle| __inherited.with_font_size(13.0).with_color(theme.get().on_primary) },
                        )?
                    };
                    let __text_32 = {
                        Text::declaring(
                            || "Features".to_string(),
                            LayoutStyle::new(),
                            { let theme = theme.clone(); move |__inherited: TextStyle| __inherited.with_font_size(13.0).with_color(theme.get().on_dark) },
                        )?
                    };
                    let __text_33 = {
                        Text::declaring(
                            || "Gallery".to_string(),
                            LayoutStyle::new(),
                            { let theme = theme.clone(); move |__inherited: TextStyle| __inherited.with_font_size(13.0).with_color(theme.get().on_dark) },
                        )?
                    };
                    Container::new(LayoutStyle::new().flex_column().gap(6.0).min_width(140.0), children![__text_31, __text_32, __text_33])?
                };
                let __col_18 = {
                    let __text_34 = {
                        Text::declaring(
                            || "Developers".to_string(),
                            LayoutStyle::new(),
                            { let theme = theme.clone(); move |__inherited: TextStyle| __inherited.with_font_size(13.0).with_color(theme.get().on_primary) },
                        )?
                    };
                    let __text_35 = {
                        Text::declaring(
                            || "Docs".to_string(),
                            LayoutStyle::new(),
                            { let theme = theme.clone(); move |__inherited: TextStyle| __inherited.with_font_size(13.0).with_color(theme.get().on_dark) },
                        )?
                    };
                    let __text_36 = {
                        Text::declaring(
                            || "Examples".to_string(),
                            LayoutStyle::new(),
                            { let theme = theme.clone(); move |__inherited: TextStyle| __inherited.with_font_size(13.0).with_color(theme.get().on_dark) },
                        )?
                    };
                    Container::new(LayoutStyle::new().flex_column().gap(6.0).min_width(140.0), children![__text_34, __text_35, __text_36])?
                };
                Container::new(style_footwrap(), children![__col_16, __col_17, __col_18])?
            };
            StyledContainer::new(style_footband(), { let theme = theme.clone(); move |_| RectStyle::default().with_fill(theme.get().dark).with_radius(BorderRadius::zero()) }, children![__row_9])?
        };
        Container::new(style_page(), children![__sbox_0, __sbox_1, __sbox_2, __sbox_7, __sbox_8, __sbox_9, __sbox_10, __sbox_11])?
    };
    Ok(Box::new(__col_0))
}

#[allow(dead_code, unused_variables, unused_mut)]
pub fn home_preview_0() -> Result<Box<dyn LayoutItem>, LayoutError> {
    #[allow(unused_imports)] use telar::use_theme;
    #[allow(unused_variables)] let theme = telar::Theme::<theme::LandingTheme>::default();
    let __node_0 = home(HomeProps::props().build(), Children::default())?;
    Ok(Box::new(__node_0))
}

pub const HOME_PREVIEW_ENTRIES: &[::telar::PreviewEntry] = &[
    ::telar::PreviewEntry { component_name: "home", preview_name: "Landing — full page", build: home_preview_0, surface: None },
];
