// Generated by telar-transpiler — do not edit manually
#![allow(clippy::all)]
#![allow(noop_method_call)]
#[allow(unused_imports)] use telar::*;
#[allow(unused_imports)] use crate::*;
#[allow(unused_imports)] use crate::shared::components::card::{card, CardProps};
#[allow(unused_imports)] use crate::shared::components::code_line::{code_line, CodeLineProps};
#[allow(unused_imports)] use crate::shared::components::doc_header::{doc_header, DocHeaderProps};
#[allow(unused_imports)] use crate::shared::components::example::{example, ExampleProps};
#[allow(unused_imports)] use crate::shared::components::prop_row::{prop_row, PropRowProps};

#[derive(::telar::Props)]
pub struct ReducedMotionProps {}

#[allow(dead_code, unused_variables, unused_mut)]
pub fn reduced_motion(props: ReducedMotionProps, children: Children) -> Result<Box<dyn LayoutItem>, LayoutError> {
    let __owner = telar::owner_scope();
    #[allow(unused_imports)] use telar::use_theme;
    #[allow(unused_variables)] let theme = telar::Theme::<core::theme::SandboxTheme>::default();

    fn reading(value: Option<bool>) -> String {
        match value {
            Some(true) => "less motion".to_string(),
            Some(false) => "full motion".to_string(),
            None => "unknown".to_string(),
        }
    }

    let system = memo(|| reading(telar::use_system_reduced_motion()));
    let chosen = memo(|| match telar::use_reduced_motion_override() {
        None => "follow the system".to_string(),
        forced => reading(forced),
    });
    let effective = memo(|| reading(telar::use_reduced_motion()));
    let pulse = signal(0.0f32);

    let __col_0 = {
        let __node_0 = doc_header(DocHeaderProps::props().kicker("FOUNDATIONS").title("Reduced motion").desc("Less motion is the system's to say until the person says otherwise in the app. An override wins over the system while it is set, holds through every change the system reports, and is kept between runs; clearing it hands the choice back.").build(), Children::default())?;
        let __node_1 = {
            let __deferred = Children::new(
                {
                    let system = system.clone();
                    let theme = theme.clone();
                    let chosen = chosen.clone();
                    let effective = effective.clone();
                move || {
                    let system = system.clone();
                    let theme = theme.clone();
                    let chosen = chosen.clone();
                    let effective = effective.clone();
                    let mut __slots = Slots::new();
                    let mut __children: Vec<Box<dyn LayoutItem>> = Vec::new();
                    let __node_2 = {
                        let __deferred = Children::new(
                            {
                                let system = system.clone();
                                let theme = theme.clone();
                                let chosen = chosen.clone();
                                let effective = effective.clone();
                            move || {
                                let system = system.clone();
                                let theme = theme.clone();
                                let chosen = chosen.clone();
                                let effective = effective.clone();
                                let mut __slots = Slots::new();
                                let mut __children: Vec<Box<dyn LayoutItem>> = Vec::new();
                                let __text_0 = {
                                    let system = system.clone();
                                    Text::declaring(
                                        move || format!("system · {}", { system.get() }),
                                        LayoutStyle::new(),
                                        { let theme = theme.clone(); move |__inherited: TextStyle| __inherited.with_font_size(15.0).with_color(theme.get().ink) },
                                    )?
                                };
                                __children.push(box_item(__text_0));
                                let __text_1 = {
                                    let chosen = chosen.clone();
                                    Text::declaring(
                                        move || format!("the app's choice · {}", { chosen.get() }),
                                        LayoutStyle::new(),
                                        { let theme = theme.clone(); move |__inherited: TextStyle| __inherited.with_font_size(15.0).with_color(theme.get().ink) },
                                    )?
                                };
                                __children.push(box_item(__text_1));
                                let __text_2 = {
                                    let effective = effective.clone();
                                    Text::declaring(
                                        move || format!("in effect · {}", { effective.get() }),
                                        LayoutStyle::new(),
                                        { let theme = theme.clone(); move |__inherited: TextStyle| __inherited.with_font_size(15.0).with_color(theme.get().primary) },
                                    )?
                                };
                                __children.push(box_item(__text_2));
                                let __row_0 = {
                                    let __node_3 = button(ButtonProps::props().label("Follow the system").ghost(true).on_press(std::rc::Rc::new(move || telar::set_reduced_motion_override(None))).build(), Children::default())?;
                                    let __node_4 = button(ButtonProps::props().label("Less motion").ghost(true).on_press(std::rc::Rc::new(move || telar::set_reduced_motion_override(Some(true)))).build(), Children::default())?;
                                    let __node_5 = button(ButtonProps::props().label("Full motion").ghost(true).on_press(std::rc::Rc::new(move || telar::set_reduced_motion_override(Some(false)))).build(), Children::default())?;
                                    Container::new(LayoutStyle::new().flex_row().gap(8.0).flex_wrap(), children![__node_3, __node_4, __node_5])?
                                };
                                __children.push(box_item(__row_0));
                                let __text_3 = {
                                    Text::declaring(
                                        || "The choice is kept in the target's preference store: a file in the app's config directory, or localStorage on the web.".to_string(),
                                        LayoutStyle::new(),
                                        { let theme = theme.clone(); move |__inherited: TextStyle| __inherited.with_font_size(12.0).with_color(theme.get().muted) },
                                    )?
                                };
                                __children.push(box_item(__text_3));
                                __slots.extend_default(__children);
                                Ok(__slots)
                            }
                            }
                        );
                        card(CardProps::props().gap(8.0).build(), __deferred)?
                    };
                    __children.push(box_item(__node_2));
                    let __node_6 = code_line(CodeLineProps::props().code("set_reduced_motion_override(Some(true))   ·   use_reduced_motion()   ·   use_system_reduced_motion()").build(), Children::default())?;
                    __children.push(box_item(__node_6));
                    __slots.extend_default(__children);
                    Ok(__slots)
                }
                }
            );
            example(ExampleProps::props().title("What the app runs with").build(), __deferred)?
        };
        let __node_7 = {
            let __deferred = Children::new(
                {
                    let theme = theme.clone();
                    let pulse = pulse.clone();
                move || {
                    let theme = theme.clone();
                    let pulse = pulse.clone();
                    let mut __slots = Slots::new();
                    let mut __children: Vec<Box<dyn LayoutItem>> = Vec::new();
                    let __node_8 = {
                        let __deferred = Children::new(
                            {
                                let theme = theme.clone();
                                let pulse = pulse.clone();
                            move || {
                                let theme = theme.clone();
                                let pulse = pulse.clone();
                                let mut __slots = Slots::new();
                                let mut __children: Vec<Box<dyn LayoutItem>> = Vec::new();
                                let __row_1 = {
                                    let __node_9 = button(ButtonProps::props().label("Slide").fill(Reactive::of({ let theme = theme.clone(); move || theme.get().primary })).on_press(std::rc::Rc::new({ let pulse = pulse.clone(); move || pulse.set(if pulse.get() < 0.5 { 1.0 } else { 0.0 }) })).build(), Children::default())?;
                                    let __node_10 = spinner(SpinnerProps::props().size(20.0).build(), Children::default())?;
                                    Container::new(LayoutStyle::new().flex_row().gap(12.0).align_items(AlignItems::CENTER), children![__node_9, __node_10])?
                                };
                                __children.push(box_item(__row_1));
                                let __sbox_0 = {
                                    let __sbox_1 = {
                                        let __transition_0 = motion::Animated::new(((pulse.get() * 220.0)) as f32, motion::tween(std::time::Duration::from_millis(1200), motion::Easing::EaseInOut));
                                        StyledContainer::new(LayoutStyle::new().flex_column().height(12.0).width(40.0), { let theme = theme.clone(); move |_| RectStyle::default().with_fill(theme.get().primary).with_radius(BorderRadius::all(6.0)) }, children![])?.with_transform({ let pulse = pulse.clone(); move |__r: Rect| box_transform(__r, (0) as f32, (1) as f32, (1) as f32, { __transition_0.retarget(((pulse.get() * 220.0)) as f32); __transition_0.get() }, (0) as f32) })
                                    };
                                    StyledContainer::new(LayoutStyle::new().flex_column().height(12.0).width(260.0), { let theme = theme.clone(); move |_| RectStyle::default().with_fill(theme.get().surface_alt).with_radius(BorderRadius::all(6.0)) }, children![__sbox_1])?
                                };
                                __children.push(box_item(__sbox_0));
                                let __text_4 = {
                                    Text::declaring(
                                        || "With less motion in effect the bar jumps straight to its end and the spinner rests; scroll momentum keeps moving.".to_string(),
                                        LayoutStyle::new(),
                                        { let theme = theme.clone(); move |__inherited: TextStyle| __inherited.with_font_size(12.0).with_color(theme.get().muted) },
                                    )?
                                };
                                __children.push(box_item(__text_4));
                                __slots.extend_default(__children);
                                Ok(__slots)
                            }
                            }
                        );
                        card(CardProps::props().gap(12.0).build(), __deferred)?
                    };
                    __children.push(box_item(__node_8));
                    let __node_11 = code_line(CodeLineProps::props().code("motion::follow_reduced_motion(false)   // only for an app that tones its motion down itself").build(), Children::default())?;
                    __children.push(box_item(__node_11));
                    __slots.extend_default(__children);
                    Ok(__slots)
                }
                }
            );
            example(ExampleProps::props().title("Every animation follows the value in effect").build(), __deferred)?
        };
        let __node_12 = {
            let __deferred = Children::new(
                move || {
                    let mut __slots = Slots::new();
                    let mut __children: Vec<Box<dyn LayoutItem>> = Vec::new();
                    let __col_1 = {
                        let __node_13 = prop_row(PropRowProps::props().name("set_reduced_motion_override").values("Option<bool>").about("Some(true) less motion, Some(false) full motion, None follows the system.").build(), Children::default())?;
                        let __node_14 = prop_row(PropRowProps::props().name("use_reduced_motion").values("Option<bool>").about("the value in effect, read reactively; None only while both are unknown.").build(), Children::default())?;
                        let __node_15 = prop_row(PropRowProps::props().name("use_system_reduced_motion").values("Option<bool>").about("what the system reported, ignoring the override.").build(), Children::default())?;
                        let __node_16 = prop_row(PropRowProps::props().name("use_reduced_motion_override").values("Option<bool>").about("the app's choice itself.").build(), Children::default())?;
                        Container::new(LayoutStyle::new().flex_column().gap(6.0), children![__node_13, __node_14, __node_15, __node_16])?
                    };
                    __children.push(box_item(__col_1));
                    __slots.extend_default(__children);
                    Ok(__slots)
                }
            );
            example(ExampleProps::props().title("API").build(), __deferred)?
        };
        Container::new(LayoutStyle::new().flex_column().gap(20.0), children![__node_0, __node_1, __node_7, __node_12])?
    };
    Ok(Box::new(__col_0))
}
