[package]
name = "renderer-hardware"
version = "0.1.0"
edition = "2024"

[dependencies]
renderer-core = { workspace = true }
raw-window-handle = { workspace = true }
wgpu = "29.0.3"
pollster = "0.4"
bytemuck = { workspace = true, features = ["derive"] }
renderer-text = { workspace = true }
lyon = "1.0.19"
tracing = { workspace = true }
geometry-core = { workspace = true }
rustc-hash = { workspace = true }

[dev-dependencies]
criterion = "0.8.2"

[[bench]]
name = "render_frame"
harness = false
