// Generated by telar-transpiler — do not edit manually
#![allow(clippy::all)]
#![allow(noop_method_call)]
#[allow(unused_imports)] use telar::*;
#[allow(unused_imports)] use telar_icons::*;
#[allow(unused_imports)] use crate::*;

#[derive(::telar::Props)]
pub struct GreetingCardProps {
    #[props(default)]
    pub name: &'static str,
}

#[allow(dead_code, unused_variables, unused_mut)]
pub fn greeting_card(props: GreetingCardProps, children: Children) -> Result<Box<dyn LayoutItem>, LayoutError> {
    let __owner = telar::owner_scope();
    let __row_0 = {
        let __svg_0 = {
            Svg::new(
                LayoutStyle::new().width(24.0).height(24.0),
                move || std::sync::Arc::clone(&crate::__rsx_assets::ASSET_7B792050),
                || None,
                move || ObjectFit::Contain,
            )?
        };
        let __node_0 = icon(IconProps::props().name(("fixture:dot", ::std::sync::Arc::clone(&crate::__rsx_assets::ASSET_6504A2AF), true)).size(16.0).build(), Children::default())?;
        let __text_0 = {
            Text::declaring(
                move || format!("{}", { t!("greeting", name = props.name) }),
                LayoutStyle::new(),
                move |__inherited: TextStyle| __inherited.with_font_size(14.0).with_color(::telar::use_theme_tokens().on_primary()),
            )?
        };
        StyledContainer::new(LayoutStyle::new().flex_row().gap(8.0).padding_all(12.0).align_items(AlignItems::CENTER), move |_| RectStyle::default().with_fill(::telar::use_theme_tokens().primary()).with_radius(BorderRadius::all(::telar::use_theme_tokens().radius())), children![__svg_0, __node_0, __text_0])?
    };
    Ok(Box::new(__row_0))
}

::telar::__previews! {

#[allow(dead_code, unused_variables, unused_mut)]
pub fn greeting_card_preview_0(__preview: &::telar::preview::PreviewCtx) -> Result<Box<dyn LayoutItem>, LayoutError> {
    let __node_0 = greeting_card(GreetingCardProps::props().name(::telar::__preview_arg!(__preview, "name", "Ada")).__preview_actions(&__preview.actions()).build(), Children::default())?;
    Ok(Box::new(__node_0))
}

pub const GREETING_CARD_PREVIEW_ENTRIES: &[::telar::preview::PreviewEntry] = &[
    ::telar::preview::PreviewEntry::new(concat!(env!("CARGO_CRATE_NAME"), "--greeting_card--ada"), "greeting_card", "Ada", greeting_card_preview_0)
        .location(concat!(env!("CARGO_MANIFEST_DIR"), "/src/greeting_card.rsx"), 16)
        .title("Fixture/Greeting card")
        .docs("A greeting in the fixture's own catalog, beside a baked mark and a baked icon.")
        .source("[preview \"Ada\"]\ngreeting_card name:\"Ada\"", &[::telar::preview::SourceSpan::new(0, 40, 16)])
        .props(<GreetingCardProps as ::telar::preview::HasPropsSchema>::schema)
        .args(&[::telar::preview::ArgSpec::new("name").default("\"Ada\"")])
        .layout(::telar::preview::Layout::Centered),
];
}
