// Generated by telar-transpiler — do not edit manually
#![allow(clippy::all)]
#![allow(noop_method_call)]
#[allow(unused_imports)] use telar::*;
#[allow(unused_imports)] use telar_icons::*;
#[allow(unused_imports)] use crate::*;

::telar::__previews! {

#[allow(dead_code, unused_variables, unused_mut)]
pub fn tally_preview_0(__preview: &::telar::preview::PreviewCtx) -> Result<Box<dyn LayoutItem>, LayoutError> {
    let __node_0 = tally(TallyProps::props().label(::telar::__preview_arg!(__preview, "label", "Pears")).count(::telar::__preview_arg!(__preview, "count", 2u32)).__preview_actions(&__preview.actions()).build(), Children::default())?;
    Ok(Box::new(__node_0))
}

#[allow(dead_code, unused_variables, unused_mut)]
pub fn tally_preview_1(__preview: &::telar::preview::PreviewCtx) -> Result<Box<dyn LayoutItem>, LayoutError> {
    let count = ::telar::__preview_signal!(__preview, "count", 3u32);
    let __node_0 = tally(TallyProps::props().label(::telar::__preview_arg!(__preview, "label", "Plums")).count(count.clone()).__preview_actions(&__preview.actions()).build(), Children::default())?;
    Ok(Box::new(__node_0))
}

pub const TALLY_PREVIEW_ENTRIES: &[::telar::preview::PreviewEntry] = &[
    ::telar::preview::PreviewEntry::new(concat!(env!("CARGO_CRATE_NAME"), "--tally--rsx-literal"), "tally", "Rsx literal", tally_preview_0)
        .location(concat!(env!("CARGO_MANIFEST_DIR"), "/src/tally.previews.rsx"), 4)
        .title("Fixture/Tally")
        .docs("The tally written in Rust, previewed from `.rsx`.")
        .source("[preview \"Rsx literal\" matrix:(dir:[ltr rtl] count:[1 2])]\ntally label:\"Pears\" count:2u32", &[::telar::preview::SourceSpan::new(0, 89, 4)])
        .props(<TallyProps as ::telar::preview::HasPropsSchema>::schema)
        .args(&[::telar::preview::ArgSpec::new("label").default("\"Pears\""), ::telar::preview::ArgSpec::new("count").default("2")])
        .layout(::telar::preview::Layout::Centered)
        .tags(&["rsx"])
        .matrix(::telar::preview::Matrix::Axes(&[::telar::preview::Axis::Dir(&[::telar::Direction::Ltr, ::telar::Direction::Rtl]), ::telar::preview::Axis::Arg("count", &["1", "2"])])),
    ::telar::preview::PreviewEntry::new(concat!(env!("CARGO_CRATE_NAME"), "--tally--rsx-bound"), "tally", "Rsx bound", tally_preview_1)
        .location(concat!(env!("CARGO_MANIFEST_DIR"), "/src/tally.previews.rsx"), 7)
        .title("Fixture/Tally")
        .docs("The tally written in Rust, previewed from `.rsx`.")
        .source("[preview \"Rsx bound\" args(count:3u32) layout:padded]\ntally label:\"Plums\" count:$count\n\n[play]\ncanvas.expect_text(\"Plums · 3\")?;", &[::telar::preview::SourceSpan::new(0, 128, 7)])
        .props(<TallyProps as ::telar::preview::HasPropsSchema>::schema)
        .args(&[::telar::preview::ArgSpec::new("count").binding(::telar::preview::ArgBinding::Live).default("3"), ::telar::preview::ArgSpec::new("label").default("\"Plums\"")])
        .layout(::telar::preview::Layout::Padded)
        .tags(&["rsx"]),
];
}
