// Generated by telar-transpiler — do not edit manually
#![allow(clippy::all)]
#[allow(unused_imports)] use telar::*;
#[allow(unused_imports)] use crate::*;

// The standard surface panel used across the sandbox. The card recipe (fill:theme.surface stroke:theme.border
// radius:12 pad:16) lives here once instead of inline at every call site. `gap` spaces the stacked
// body children (pass 0 for a single child). `pad` overrides the 16px inset via the `= 16.0` inline
// default, so an omitted `pad` is 16 while `pad:0` genuinely means zero. An optional "header" slot renders above the body.
#[derive(::telar::Props)]
pub struct SharedComponentsCardProps {
    #[props(default)]
    pub gap: f32,
    #[props(default = 16.0)]
    pub pad: f32,
}

#[allow(dead_code, unused_variables, unused_mut)]
pub fn shared_components_card(props: SharedComponentsCardProps, children: Children) -> Result<Box<dyn LayoutItem>, LayoutError> {
    let __owner = telar::owner_scope();
    #[allow(unused_imports)] use telar::use_theme;
    let mut __slots = children.build()?;
    let __sbox_0 = {
        let mut __children: Vec<Box<dyn LayoutItem>> = Vec::new();
        __children.extend(__slots.take("header"));
        __children.extend(__slots.take_default());
        StyledContainer::new(LayoutStyle::new().flex_column().padding_all(props.pad).gap(props.gap), move |_| RectStyle { fill: Some(Paint::Solid(use_theme::<core::theme::SandboxTheme>().surface())), border: Some(Border { paint: Paint::Solid(use_theme::<core::theme::SandboxTheme>().border()), widths: [1.0; 4] }), shadow: None, radius: BorderRadius::all(12.0) }, __children)?
    };
    Ok(Box::new(__sbox_0))
}

#[allow(dead_code, unused_variables, unused_mut)]
pub fn shared_components_card_preview_0() -> Result<Box<dyn LayoutItem>, LayoutError> {
    #[allow(unused_imports)] use telar::use_theme;
    let __node_0 = {
        let __deferred = Children::new(
            move || {
                let mut __slots = Slots::new();
                let mut __children: Vec<Box<dyn LayoutItem>> = Vec::new();
                let __text_0 = {
                    Text::declaring(
                        || "Header".to_string(),
                        LayoutStyle::new(),
                        move |__inherited: TextStyle| __inherited.with_font_size(16.0).with_color(use_theme::<core::theme::SandboxTheme>().ink()),
                    )?
                };
                __slots.push(Some("header"), box_item(__text_0));
                let __text_1 = {
                    Text::declaring(
                        || "A card is the standard surface panel.".to_string(),
                        LayoutStyle::new(),
                        move |__inherited: TextStyle| __inherited.with_font_size(13.0).with_color(use_theme::<core::theme::SandboxTheme>().muted()),
                    )?
                };
                __children.push(box_item(__text_1));
                let __text_2 = {
                    Text::declaring(
                        || "Bare children stack with the gap you pass; slot:\"header\" pins a header on top.".to_string(),
                        LayoutStyle::new(),
                        move |__inherited: TextStyle| __inherited.with_font_size(13.0).with_color(use_theme::<core::theme::SandboxTheme>().muted()),
                    )?
                };
                __children.push(box_item(__text_2));
                __slots.extend_default(__children);
                Ok(__slots)
            }
        );
        card(CardProps::props().gap(8.0).build(), __deferred)?
    };
    Ok(Box::new(__node_0))
}

pub const SHARED_COMPONENTS_CARD_PREVIEW_ENTRIES: &[::telar::PreviewEntry] = &[
    ::telar::PreviewEntry { component_name: "shared_components_card", preview_name: "Card", build: shared_components_card_preview_0, surface: None },
];
