// Generated by telar-transpiler — do not edit manually
#![allow(clippy::all)]
#[allow(unused_imports)] use telar::*;
#[allow(unused_imports)] use super::*;

// A one-line `.rsx` code snippet in a dark pill. Snippets use single quotes for string
// literals (real `.rsx` uses double quotes) because a `"` would close the markup string early.
#[derive(::telar::Props)]
pub struct SharedComponentsCodeLineProps {
    #[props(default)]
    pub code: &'static str,
}

#[allow(dead_code, unused_variables, unused_mut)]
pub fn shared_components_code_line(props: SharedComponentsCodeLineProps) -> Result<Box<dyn LayoutItem>, LayoutError> {
    let __owner = telar::owner_scope();
    #[allow(unused_imports)] use telar::use_theme;
    let __sbox_0 = {
        let __text_0 = {
            Text::declaring(
                move || format!("{}", { props.code }),
                LayoutStyle::new(),
                move |__inherited: TextStyle| __inherited.with_font_size(12.0).with_color(use_theme::<core::theme::SandboxTheme>().code_fg),
            )?
        };
        StyledContainer::new(LayoutStyle::new().flex_column().padding_horizontal(12.0).padding_vertical(8.0), move |_| RectStyle::default().with_fill(use_theme::<core::theme::SandboxTheme>().code_bg).with_radius(BorderRadius::all(8.0)), children![__text_0])?
    };
    Ok(Box::new(__sbox_0))
}

#[allow(dead_code, unused_variables, unused_mut)]
pub fn shared_components_code_line_preview_0() -> Result<Box<dyn LayoutItem>, LayoutError> {
    #[allow(unused_imports)] use telar::use_theme;
    let __node_0 = code_line(CodeLineProps::props().code("box fill:primary radius:8 width:120 height:80").build())?;
    Ok(Box::new(__node_0))
}

pub const SHARED_COMPONENTS_CODE_LINE_PREVIEW_ENTRIES: &[::telar::PreviewEntry] = &[
    ::telar::PreviewEntry { component_name: "shared_components_code_line", preview_name: "Code line", build: shared_components_code_line_preview_0, surface: None },
];
