// Generated by telar-transpiler — do not edit manually
#![allow(clippy::all)]
#[allow(unused_imports)] use telar::*;
#[allow(unused_imports)] use crate::*;

#[derive(::telar::Props)]
pub struct SharedComponentsDocHeaderProps {
    #[props(default)]
    pub kicker: &'static str,
    #[props(default)]
    pub title: &'static str,
    #[props(default)]
    pub desc: &'static str,
}

#[allow(dead_code, unused_variables, unused_mut)]
pub fn shared_components_doc_header(props: SharedComponentsDocHeaderProps, children: Children) -> Result<Box<dyn LayoutItem>, LayoutError> {
    let __owner = telar::owner_scope();
    #[allow(unused_imports)] use telar::use_theme;
    let __col_0 = {
        let __text_0 = {
            Text::declaring(
                move || format!("{}", { props.kicker }),
                LayoutStyle::new(),
                move |__inherited: TextStyle| __inherited.with_font_size(12.0).with_color(use_theme::<core::theme::SandboxTheme>().primary()),
            )?
        };
        let __text_1 = {
            Text::declaring(
                move || format!("{}", { props.title }),
                LayoutStyle::new(),
                move |__inherited: TextStyle| __inherited.with_font_size(26.0).with_color(use_theme::<core::theme::SandboxTheme>().ink()),
            )?
        };
        let __text_2 = {
            Text::declaring(
                move || format!("{}", { props.desc }),
                LayoutStyle::new().max_width(760.0),
                move |__inherited: TextStyle| __inherited.with_font_size(14.0).with_color(use_theme::<core::theme::SandboxTheme>().muted()),
            )?
        };
        Container::new(LayoutStyle::new().flex_column().gap(6.0), children![__text_0, __text_1, __text_2])?
    };
    Ok(Box::new(__col_0))
}

#[allow(dead_code, unused_variables, unused_mut)]
pub fn shared_components_doc_header_preview_0() -> Result<Box<dyn LayoutItem>, LayoutError> {
    #[allow(unused_imports)] use telar::use_theme;
    let __node_0 = doc_header(DocHeaderProps::props().kicker("FOUNDATIONS").title("Layout").desc("Flexbox rows and columns with gaps, padding, alignment and growth.").build(), Children::default())?;
    Ok(Box::new(__node_0))
}

pub const SHARED_COMPONENTS_DOC_HEADER_PREVIEW_ENTRIES: &[::telar::PreviewEntry] = &[
    ::telar::PreviewEntry { component_name: "shared_components_doc_header", preview_name: "Doc header", build: shared_components_doc_header_preview_0, surface: None },
];
