// Generated by telar-transpiler — do not edit manually
#![allow(clippy::all)]
#[allow(unused_imports)] use telar::*;
#[allow(unused_imports)] use crate::*;

// One documentation row for an attribute: its name, accepted values, and a short description.
#[derive(::telar::Props)]
pub struct PropRowProps {
    #[props(default)]
    pub name: &'static str,
    #[props(default)]
    pub values: &'static str,
    #[props(default)]
    pub about: &'static str,
}

#[allow(dead_code, unused_variables, unused_mut)]
pub fn prop_row(props: PropRowProps, children: Children) -> Result<Box<dyn LayoutItem>, LayoutError> {
    let __owner = telar::owner_scope();
    #[allow(unused_imports)] use telar::use_theme;
    #[allow(unused_variables)] let theme = telar::Theme::<core::theme::SandboxTheme>::default();
    let __row_0 = {
        let __text_0 = {
            Text::declaring(
                move || format!("{}", { props.name }),
                LayoutStyle::new().width(120.0),
                { let theme = theme.clone(); move |__inherited: TextStyle| __inherited.with_font_size(13.0).with_color(theme.get().ink) },
            )?
        };
        let __text_1 = {
            Text::declaring(
                move || format!("{}", { props.values }),
                LayoutStyle::new().width(190.0),
                { let theme = theme.clone(); move |__inherited: TextStyle| __inherited.with_font_size(13.0).with_color(theme.get().primary) },
            )?
        };
        let __text_2 = {
            Text::declaring(
                move || format!("{}", { props.about }),
                LayoutStyle::new().flex_grow(1.0),
                { let theme = theme.clone(); move |__inherited: TextStyle| __inherited.with_font_size(13.0).with_color(theme.get().muted) },
            )?
        };
        Container::new(LayoutStyle::new().flex_row().gap(12.0).align_items(AlignItems::START), children![__text_0, __text_1, __text_2])?
    };
    Ok(Box::new(__row_0))
}

#[allow(dead_code, unused_variables, unused_mut)]
pub fn prop_row_preview_0() -> Result<Box<dyn LayoutItem>, LayoutError> {
    #[allow(unused_imports)] use telar::use_theme;
    #[allow(unused_variables)] let theme = telar::Theme::<core::theme::SandboxTheme>::default();
    let __node_0 = prop_row(PropRowProps::props().name("align").values("start · center · end · stretch").about("Cross-axis alignment of children.").build(), Children::default())?;
    Ok(Box::new(__node_0))
}

pub const PROP_ROW_PREVIEW_ENTRIES: &[::telar::PreviewEntry] = &[
    ::telar::PreviewEntry { component_name: "prop_row", preview_name: "Prop row", build: prop_row_preview_0, surface: None },
];
