// Generated by telar-transpiler — do not edit manually
#![allow(clippy::all)]
#[allow(unused_imports)] use telar::*;
#[allow(unused_imports)] use super::*;

#[derive(::telar::Props)]
pub struct SharedComponentsStatProps {
    #[props(default)]
    pub value: &'static str,
    #[props(default)]
    pub label: &'static str,
}

#[allow(dead_code, unused_variables, unused_mut)]
pub fn shared_components_stat(props: SharedComponentsStatProps) -> Result<Box<dyn LayoutItem>, LayoutError> {
    let __owner = telar::owner_scope();
    #[allow(unused_imports)] use telar::use_theme;
    let __sbox_0 = {
        let __text_0 = {
            Text::declaring(
                move || format!("{}", { props.value }),
                LayoutStyle::new(),
                move |__inherited: TextStyle| __inherited.with_font_size(28.0).with_color(use_theme::<core::theme::SandboxTheme>().primary()),
            )?
        };
        let __text_1 = {
            Text::declaring(
                move || format!("{}", { props.label }),
                LayoutStyle::new(),
                move |__inherited: TextStyle| __inherited.with_font_size(12.0).with_color(use_theme::<core::theme::SandboxTheme>().muted()),
            )?
        };
        StyledContainer::new(LayoutStyle::new().flex_column().flex_grow(1.0).min_width(130.0).padding_all(18.0).gap(4.0).align_items(AlignItems::CENTER), move |_| RectStyle { fill: Some(Paint::Solid(use_theme::<core::theme::SandboxTheme>().surface())), border: Some(Border { paint: Paint::Solid(use_theme::<core::theme::SandboxTheme>().border()), widths: [1.0; 4] }), shadow: None, radius: BorderRadius::all(14.0) }, children![__text_0, __text_1])?
    };
    Ok(Box::new(__sbox_0))
}

#[allow(dead_code, unused_variables, unused_mut)]
pub fn shared_components_stat_preview_0() -> Result<Box<dyn LayoutItem>, LayoutError> {
    #[allow(unused_imports)] use telar::use_theme;
    let __node_0 = stat(StatProps::props().value("60 fps").label("software + wgpu").build())?;
    Ok(Box::new(__node_0))
}

pub const SHARED_COMPONENTS_STAT_PREVIEW_ENTRIES: &[::telar::PreviewEntry] = &[
    ::telar::PreviewEntry { component_name: "shared_components_stat", preview_name: "Stat", build: shared_components_stat_preview_0, surface: None },
];
