[package]
name = "rsx"
version = "0.1.0"
edition = "2024"

[features]
default = ["runtime"]
runtime = [
    "dep:platform-core",
    "dep:platform-winit",
    "dep:renderer-core",
    "dep:renderer-software",
    "dep:renderer-hardware",
]

[dependencies]
serde = { workspace = true }
toml = { workspace = true }
dirs = "6.0.0"
platform-core = { workspace = true, optional = true }
platform-winit = { workspace = true, optional = true }
renderer-core = { workspace = true, optional = true }
renderer-software = { workspace = true, optional = true }
renderer-hardware = { workspace = true, optional = true }
reactive-core = { workspace = true }
services-core = { workspace = true }
layout-core = { workspace = true }
ui-core = { workspace = true }
tracing = { workspace = true }
