[package]
name = "rsx"
version = "0.1.0"
edition = "2024"

[features]
default = ["runtime"]
dev = ["dep:rsx-devtools"]
runtime = [
    "dep:platform-core",
    "dep:renderer-core",
    "dep:renderer-software",
    "dep:rsx-devtools",
]

[dependencies]
serde = { workspace = true }
toml = { workspace = true }
platform-core = { workspace = true, optional = true }
renderer-core = { workspace = true, optional = true }
renderer-software = { workspace = true, optional = true }
rsx-devtools = { workspace = true, optional = true }
reactive-core = { workspace = true }
renderer-hardware = { workspace = true }
services-core = { workspace = true }
layout-core = { workspace = true }
theme-core = { workspace = true }
ui-core = { workspace = true }
tracing = { workspace = true }
geometry-core = { workspace = true }

[target.'cfg(not(target_os = "android"))'.dependencies]
dirs = "6.0.0"
platform-winit = { workspace = true }

[target.'cfg(target_os = "android")'.dependencies]
platform-android = { workspace = true }
