[package]
name = "telar-platform-android"
version = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
description = "Android platform backend for Telar, built on android-activity."
keywords = ["telar", "android", "platform", "mobile", "gui"]
categories = ["gui", "os"]
readme = "README.md"
license = { workspace = true }
repository = { workspace = true }

[dependencies]
platform-core = { workspace = true }
services-core = { workspace = true }

raw-window-handle = { workspace = true }

[target.'cfg(target_os = "android")'.dependencies]
platform-winit = { workspace = true }

android-activity = { version = "0.6", features = ["native-activity"] }
libc = { workspace = true }
paranoid-android = "0.2.2"
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
winit = { workspace = true, features = ["android-native-activity"] }
