[package]
name = "platform-android"
version = "0.1.0"
edition = "2024"

[dependencies]
platform-core = { workspace = true }
services-core = { workspace = true }
raw-window-handle = { workspace = true }

[target.'cfg(target_os = "android")'.dependencies]
winit = { version = "0.30", default-features = false, features = [
    "android-native-activity",
    "rwh_06",
] }
android-activity = { version = "0.6", features = ["native-activity"] }
android_logger = "0.15"
log = "0.4"
