// Generated by telar-transpiler — do not edit manually
#![allow(clippy::all)]
#![allow(noop_method_call)]
#[allow(unused_imports)] use telar::*;
#[allow(unused_imports)] use crate::*;

#[derive(::telar::Props)]
pub struct FeatureCardProps {
    #[props(default)]
    pub icon: &'static str,
    #[props(default)]
    pub title: &'static str,
    #[props(default)]
    pub body: &'static str,
}

#[allow(dead_code, unused_variables, unused_mut)]
pub fn feature_card(props: FeatureCardProps, children: Children) -> Result<Box<dyn LayoutItem>, LayoutError> {
    let __owner = telar::owner_scope();
    #[allow(unused_imports)] use telar::use_theme;
    #[allow(unused_variables)] let theme = telar::Theme::<core::theme::SandboxTheme>::default();
    let __sbox_0 = {
        let __text_0 = {
            Text::declaring(
                move || format!("{}", { props.icon }),
                LayoutStyle::new(),
                move |__inherited: TextStyle| __inherited.with_font_size(28.0),
            )?
        };
        let __text_1 = {
            Text::declaring(
                move || format!("{}", { props.title }),
                LayoutStyle::new(),
                { let theme = theme.clone(); move |__inherited: TextStyle| __inherited.with_font_size(16.0).with_color(theme.get().ink) },
            )?
        };
        let __text_2 = {
            Text::declaring(
                move || format!("{}", { props.body }),
                LayoutStyle::new(),
                { let theme = theme.clone(); move |__inherited: TextStyle| __inherited.with_font_size(13.0).with_color(theme.get().muted) },
            )?
        };
        StyledContainer::new(LayoutStyle::new().flex_column().flex_grow(1.0).min_width(170.0).padding_all(20.0).gap(8.0).bordered(), { let theme = theme.clone(); move |_| RectStyle { fill: Some(Paint::Solid(theme.get().surface)), border: Some(Border { paint: Paint::Solid(theme.get().border), widths: [1.0; 4] }), shadow: None, radius: BorderRadius::all(16.0) } }, children![__text_0, __text_1, __text_2])?
    };
    Ok(Box::new(__sbox_0))
}

#[allow(dead_code, unused_variables, unused_mut)]
pub fn feature_card_preview_0() -> Result<Box<dyn LayoutItem>, LayoutError> {
    #[allow(unused_imports)] use telar::use_theme;
    #[allow(unused_variables)] let theme = telar::Theme::<core::theme::SandboxTheme>::default();
    let __node_0 = feature_card(FeatureCardProps::props().icon("⚡").title("Fast").body("Software and wgpu renderers with dirty-tracking and scroll-blit detection.").build(), Children::default())?;
    Ok(Box::new(__node_0))
}

pub const FEATURE_CARD_PREVIEW_ENTRIES: &[::telar::PreviewEntry] = &[
    ::telar::PreviewEntry { component_name: "feature_card", preview_name: "Feature card", build: feature_card_preview_0, surface: None },
];
