// Generated by telar-transpiler — do not edit manually
#![allow(clippy::all)]
#![allow(noop_method_call)]
#[allow(unused_imports)] use telar::*;
#[allow(unused_imports)] use crate::*;

// A panel drawn in a theme of its own. What a call site nests inside it is built where `children` stands, so it reads the panel's theme and its `Context` exactly as a child written inline would.
#[derive(Clone, Copy)]
pub struct ThemedPanelContext {
    pub mode: &'static str,
}

#[derive(::telar::Props)]
pub struct ThemedPanelProps {
    #[props(default = "midnight")]
    pub mode: &'static str,
}

#[allow(dead_code, unused_variables, unused_mut)]
pub fn themed_panel(props: ThemedPanelProps, children: Children) -> Result<Box<dyn LayoutItem>, LayoutError> {
    let __owner = telar::owner_scope();
    #[allow(unused_imports)] use telar::use_theme;
    #[allow(unused_variables)] let theme = telar::Theme::<core::theme::SandboxTheme>::default();
    #[allow(unused_imports)] use ThemedPanelContext as Context;


    let mode = props.mode;
    let palette = follow_theme(move || crate::core::theme::SandboxTheme::by_mode(mode));
    let ctx = Context { mode };

    let __col_0 = provide_theme(palette, || {
    let __col_0 = {
        let __col_1 = {
            let mut __children: Vec<Box<dyn LayoutItem>> = Vec::new();
            __children.extend(children.build_slot_with(None, ctx)?);
            Container::new(LayoutStyle::new().flex_column().gap(6.0), __children)?
        };
        StyledContainer::new(LayoutStyle::new().flex_column().padding_all(14.0), { let theme = theme.clone(); move |_| RectStyle::default().with_fill(theme.get().surface).with_radius(BorderRadius::all(10.0)) }, children![__col_1])?
    };
        Ok(Box::new(__col_0) as Box<dyn LayoutItem>)
    })?;
    Ok(Box::new(__col_0))
}

#[allow(dead_code, unused_variables, unused_mut)]
pub fn themed_panel_preview_0() -> Result<Box<dyn LayoutItem>, LayoutError> {
    #[allow(unused_imports)] use telar::use_theme;
    #[allow(unused_variables)] let theme = telar::Theme::<core::theme::SandboxTheme>::default();
    let __node_0 = {
        let __deferred = Children::per_slot(
            {
                let theme = theme.clone();
            move |__request: SlotRequest<'_>| {
                let theme = theme.clone();
                let mut __slots = Slots::new();
                let mut __children: Vec<Box<dyn LayoutItem>> = Vec::new();
                if __request.includes(None) {
                    let __text_0 = {
                        let theme = theme.clone();
                        Text::declaring(
                            move || format!("Nested at the call site, drawn in {}", { theme.get().name }),
                            LayoutStyle::new(),
                            { let theme = theme.clone(); move |__inherited: TextStyle| __inherited.with_font_size(14.0).with_color(theme.get().ink) },
                        )?
                    };
                    __children.push(box_item(__text_0));
                }
                __slots.extend_default(__children);
                Ok(__slots)
            }
            }
        );
        themed_panel(ThemedPanelProps::props().mode("pastel").build(), __deferred)?
    };
    Ok(Box::new(__node_0))
}

pub const THEMED_PANEL_PREVIEW_ENTRIES: &[::telar::PreviewEntry] = &[
    ::telar::PreviewEntry { component_name: "themed_panel", preview_name: "Themed panel", build: themed_panel_preview_0, surface: None },
];
